package com.konfigthis.client;

import com.konfigthis.client.api.AdminApi;
import com.konfigthis.client.api.AdminAppsApi;
import com.konfigthis.client.api.AdminAppsApprovedApi;
import com.konfigthis.client.api.AdminAppsRequestsApi;
import com.konfigthis.client.api.AdminAppsRestrictedApi;
import com.konfigthis.client.api.AdminConversationsApi;
import com.konfigthis.client.api.AdminConversationsEkmApi;
import com.konfigthis.client.api.AdminConversationsRestrictAccessApi;
import com.konfigthis.client.api.AdminEmojiApi;
import com.konfigthis.client.api.AdminInviteRequestsApi;
import com.konfigthis.client.api.AdminInviteRequestsApprovedApi;
import com.konfigthis.client.api.AdminInviteRequestsDeniedApi;
import com.konfigthis.client.api.AdminTeamsApi;
import com.konfigthis.client.api.AdminTeamsAdminsApi;
import com.konfigthis.client.api.AdminTeamsOwnersApi;
import com.konfigthis.client.api.AdminTeamsSettingsApi;
import com.konfigthis.client.api.AdminUsergroupsApi;
import com.konfigthis.client.api.AdminUsersApi;
import com.konfigthis.client.api.AdminUsersSessionApi;
import com.konfigthis.client.api.ApiApi;
import com.konfigthis.client.api.AppsApi;
import com.konfigthis.client.api.AppsEventAuthorizationsApi;
import com.konfigthis.client.api.AppsPermissionsApi;
import com.konfigthis.client.api.AppsPermissionsResourcesApi;
import com.konfigthis.client.api.AppsPermissionsScopesApi;
import com.konfigthis.client.api.AppsPermissionsUsersApi;
import com.konfigthis.client.api.AuthApi;
import com.konfigthis.client.api.BotsApi;
import com.konfigthis.client.api.CallsApi;
import com.konfigthis.client.api.CallsParticipantsApi;
import com.konfigthis.client.api.ChatApi;
import com.konfigthis.client.api.ChatScheduledMessagesApi;
import com.konfigthis.client.api.ConversationsApi;
import com.konfigthis.client.api.DialogApi;
import com.konfigthis.client.api.DndApi;
import com.konfigthis.client.api.EmojiApi;
import com.konfigthis.client.api.FilesApi;
import com.konfigthis.client.api.FilesCommentsApi;
import com.konfigthis.client.api.FilesRemoteApi;
import com.konfigthis.client.api.MigrationApi;
import com.konfigthis.client.api.OauthApi;
import com.konfigthis.client.api.OauthV2Api;
import com.konfigthis.client.api.PinsApi;
import com.konfigthis.client.api.ReactionsApi;
import com.konfigthis.client.api.RemindersApi;
import com.konfigthis.client.api.RtmApi;
import com.konfigthis.client.api.SearchApi;
import com.konfigthis.client.api.StarsApi;
import com.konfigthis.client.api.TeamApi;
import com.konfigthis.client.api.TeamProfileApi;
import com.konfigthis.client.api.UsergroupsApi;
import com.konfigthis.client.api.UsergroupsUsersApi;
import com.konfigthis.client.api.UsersApi;
import com.konfigthis.client.api.UsersProfileApi;
import com.konfigthis.client.api.ViewsApi;
import com.konfigthis.client.api.WorkflowsApi;

public class SlackWeb {
    private ApiClient apiClient;
    public final AdminApi admin;
    public final AdminAppsApi adminApps;
    public final AdminAppsApprovedApi adminAppsApproved;
    public final AdminAppsRequestsApi adminAppsRequests;
    public final AdminAppsRestrictedApi adminAppsRestricted;
    public final AdminConversationsApi adminConversations;
    public final AdminConversationsEkmApi adminConversationsEkm;
    public final AdminConversationsRestrictAccessApi adminConversationsRestrictAccess;
    public final AdminEmojiApi adminEmoji;
    public final AdminInviteRequestsApi adminInviteRequests;
    public final AdminInviteRequestsApprovedApi adminInviteRequestsApproved;
    public final AdminInviteRequestsDeniedApi adminInviteRequestsDenied;
    public final AdminTeamsApi adminTeams;
    public final AdminTeamsAdminsApi adminTeamsAdmins;
    public final AdminTeamsOwnersApi adminTeamsOwners;
    public final AdminTeamsSettingsApi adminTeamsSettings;
    public final AdminUsergroupsApi adminUsergroups;
    public final AdminUsersApi adminUsers;
    public final AdminUsersSessionApi adminUsersSession;
    public final ApiApi api;
    public final AppsApi apps;
    public final AppsEventAuthorizationsApi appsEventAuthorizations;
    public final AppsPermissionsApi appsPermissions;
    public final AppsPermissionsResourcesApi appsPermissionsResources;
    public final AppsPermissionsScopesApi appsPermissionsScopes;
    public final AppsPermissionsUsersApi appsPermissionsUsers;
    public final AuthApi auth;
    public final BotsApi bots;
    public final CallsApi calls;
    public final CallsParticipantsApi callsParticipants;
    public final ChatApi chat;
    public final ChatScheduledMessagesApi chatScheduledMessages;
    public final ConversationsApi conversations;
    public final DialogApi dialog;
    public final DndApi dnd;
    public final EmojiApi emoji;
    public final FilesApi files;
    public final FilesCommentsApi filesComments;
    public final FilesRemoteApi filesRemote;
    public final MigrationApi migration;
    public final OauthApi oauth;
    public final OauthV2Api oauthV2;
    public final PinsApi pins;
    public final ReactionsApi reactions;
    public final RemindersApi reminders;
    public final RtmApi rtm;
    public final SearchApi search;
    public final StarsApi stars;
    public final TeamApi team;
    public final TeamProfileApi teamProfile;
    public final UsergroupsApi usergroups;
    public final UsergroupsUsersApi usergroupsUsers;
    public final UsersApi users;
    public final UsersProfileApi usersProfile;
    public final ViewsApi views;
    public final WorkflowsApi workflows;

    public SlackWeb() {
        this(null);
    }

    public SlackWeb(Configuration configuration) {
        this.apiClient = new ApiClient(null, configuration);
        this.admin = new AdminApi(this.apiClient);
        this.adminApps = new AdminAppsApi(this.apiClient);
        this.adminAppsApproved = new AdminAppsApprovedApi(this.apiClient);
        this.adminAppsRequests = new AdminAppsRequestsApi(this.apiClient);
        this.adminAppsRestricted = new AdminAppsRestrictedApi(this.apiClient);
        this.adminConversations = new AdminConversationsApi(this.apiClient);
        this.adminConversationsEkm = new AdminConversationsEkmApi(this.apiClient);
        this.adminConversationsRestrictAccess = new AdminConversationsRestrictAccessApi(this.apiClient);
        this.adminEmoji = new AdminEmojiApi(this.apiClient);
        this.adminInviteRequests = new AdminInviteRequestsApi(this.apiClient);
        this.adminInviteRequestsApproved = new AdminInviteRequestsApprovedApi(this.apiClient);
        this.adminInviteRequestsDenied = new AdminInviteRequestsDeniedApi(this.apiClient);
        this.adminTeams = new AdminTeamsApi(this.apiClient);
        this.adminTeamsAdmins = new AdminTeamsAdminsApi(this.apiClient);
        this.adminTeamsOwners = new AdminTeamsOwnersApi(this.apiClient);
        this.adminTeamsSettings = new AdminTeamsSettingsApi(this.apiClient);
        this.adminUsergroups = new AdminUsergroupsApi(this.apiClient);
        this.adminUsers = new AdminUsersApi(this.apiClient);
        this.adminUsersSession = new AdminUsersSessionApi(this.apiClient);
        this.api = new ApiApi(this.apiClient);
        this.apps = new AppsApi(this.apiClient);
        this.appsEventAuthorizations = new AppsEventAuthorizationsApi(this.apiClient);
        this.appsPermissions = new AppsPermissionsApi(this.apiClient);
        this.appsPermissionsResources = new AppsPermissionsResourcesApi(this.apiClient);
        this.appsPermissionsScopes = new AppsPermissionsScopesApi(this.apiClient);
        this.appsPermissionsUsers = new AppsPermissionsUsersApi(this.apiClient);
        this.auth = new AuthApi(this.apiClient);
        this.bots = new BotsApi(this.apiClient);
        this.calls = new CallsApi(this.apiClient);
        this.callsParticipants = new CallsParticipantsApi(this.apiClient);
        this.chat = new ChatApi(this.apiClient);
        this.chatScheduledMessages = new ChatScheduledMessagesApi(this.apiClient);
        this.conversations = new ConversationsApi(this.apiClient);
        this.dialog = new DialogApi(this.apiClient);
        this.dnd = new DndApi(this.apiClient);
        this.emoji = new EmojiApi(this.apiClient);
        this.files = new FilesApi(this.apiClient);
        this.filesComments = new FilesCommentsApi(this.apiClient);
        this.filesRemote = new FilesRemoteApi(this.apiClient);
        this.migration = new MigrationApi(this.apiClient);
        this.oauth = new OauthApi(this.apiClient);
        this.oauthV2 = new OauthV2Api(this.apiClient);
        this.pins = new PinsApi(this.apiClient);
        this.reactions = new ReactionsApi(this.apiClient);
        this.reminders = new RemindersApi(this.apiClient);
        this.rtm = new RtmApi(this.apiClient);
        this.search = new SearchApi(this.apiClient);
        this.stars = new StarsApi(this.apiClient);
        this.team = new TeamApi(this.apiClient);
        this.teamProfile = new TeamProfileApi(this.apiClient);
        this.usergroups = new UsergroupsApi(this.apiClient);
        this.usergroupsUsers = new UsergroupsUsersApi(this.apiClient);
        this.users = new UsersApi(this.apiClient);
        this.usersProfile = new UsersProfileApi(this.apiClient);
        this.views = new ViewsApi(this.apiClient);
        this.workflows = new WorkflowsApi(this.apiClient);
    }

}
