/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AdminteamsCreateEnterpriseTeamRequest
 */
public class AdminteamsCreateEnterpriseTeamRequestTest {
    private final AdminteamsCreateEnterpriseTeamRequest model = new AdminteamsCreateEnterpriseTeamRequest();

    /**
     * Model tests for AdminteamsCreateEnterpriseTeamRequest
     */
    @Test
    public void testAdminteamsCreateEnterpriseTeamRequest() {
        // TODO: test AdminteamsCreateEnterpriseTeamRequest
    }

    /**
     * Test the property 'teamDescription'
     */
    @Test
    public void teamDescriptionTest() {
        // TODO: test teamDescription
    }

    /**
     * Test the property 'teamDiscoverability'
     */
    @Test
    public void teamDiscoverabilityTest() {
        // TODO: test teamDiscoverability
    }

    /**
     * Test the property 'teamDomain'
     */
    @Test
    public void teamDomainTest() {
        // TODO: test teamDomain
    }

    /**
     * Test the property 'teamName'
     */
    @Test
    public void teamNameTest() {
        // TODO: test teamName
    }

}
