/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AdminusergroupsAddDefaultChannelsRequest
 */
public class AdminusergroupsAddDefaultChannelsRequestTest {
    private final AdminusergroupsAddDefaultChannelsRequest model = new AdminusergroupsAddDefaultChannelsRequest();

    /**
     * Model tests for AdminusergroupsAddDefaultChannelsRequest
     */
    @Test
    public void testAdminusergroupsAddDefaultChannelsRequest() {
        // TODO: test AdminusergroupsAddDefaultChannelsRequest
    }

    /**
     * Test the property 'channelIds'
     */
    @Test
    public void channelIdsTest() {
        // TODO: test channelIds
    }

    /**
     * Test the property 'teamId'
     */
    @Test
    public void teamIdTest() {
        // TODO: test teamId
    }

    /**
     * Test the property 'usergroupId'
     */
    @Test
    public void usergroupIdTest() {
        // TODO: test usergroupId
    }

}
