/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DefsOkTrue;
import com.konfigthis.client.model.ObjsMessage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ConversationsHistoryResponse
 */
public class ConversationsHistoryResponseTest {
    private final ConversationsHistoryResponse model = new ConversationsHistoryResponse();

    /**
     * Model tests for ConversationsHistoryResponse
     */
    @Test
    public void testConversationsHistoryResponse() {
        // TODO: test ConversationsHistoryResponse
    }

    /**
     * Test the property 'channelActionsCount'
     */
    @Test
    public void channelActionsCountTest() {
        // TODO: test channelActionsCount
    }

    /**
     * Test the property 'channelActionsTs'
     */
    @Test
    public void channelActionsTsTest() {
        // TODO: test channelActionsTs
    }

    /**
     * Test the property 'hasMore'
     */
    @Test
    public void hasMoreTest() {
        // TODO: test hasMore
    }

    /**
     * Test the property 'messages'
     */
    @Test
    public void messagesTest() {
        // TODO: test messages
    }

    /**
     * Test the property 'ok'
     */
    @Test
    public void okTest() {
        // TODO: test ok
    }

    /**
     * Test the property 'pinCount'
     */
    @Test
    public void pinCountTest() {
        // TODO: test pinCount
    }

}
