/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DefsOkTrue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MigrationExchangeResponse
 */
public class MigrationExchangeResponseTest {
    private final MigrationExchangeResponse model = new MigrationExchangeResponse();

    /**
     * Model tests for MigrationExchangeResponse
     */
    @Test
    public void testMigrationExchangeResponse() {
        // TODO: test MigrationExchangeResponse
    }

    /**
     * Test the property 'enterpriseId'
     */
    @Test
    public void enterpriseIdTest() {
        // TODO: test enterpriseId
    }

    /**
     * Test the property 'invalidUserIds'
     */
    @Test
    public void invalidUserIdsTest() {
        // TODO: test invalidUserIds
    }

    /**
     * Test the property 'ok'
     */
    @Test
    public void okTest() {
        // TODO: test ok
    }

    /**
     * Test the property 'teamId'
     */
    @Test
    public void teamIdTest() {
        // TODO: test teamId
    }

    /**
     * Test the property 'userIdMap'
     */
    @Test
    public void userIdMapTest() {
        // TODO: test userIdMap
    }

}
