/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DefsOkTrue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UsersGetPresenceResponse
 */
public class UsersGetPresenceResponseTest {
    private final UsersGetPresenceResponse model = new UsersGetPresenceResponse();

    /**
     * Model tests for UsersGetPresenceResponse
     */
    @Test
    public void testUsersGetPresenceResponse() {
        // TODO: test UsersGetPresenceResponse
    }

    /**
     * Test the property 'autoAway'
     */
    @Test
    public void autoAwayTest() {
        // TODO: test autoAway
    }

    /**
     * Test the property 'connectionCount'
     */
    @Test
    public void connectionCountTest() {
        // TODO: test connectionCount
    }

    /**
     * Test the property 'lastActivity'
     */
    @Test
    public void lastActivityTest() {
        // TODO: test lastActivity
    }

    /**
     * Test the property 'manualAway'
     */
    @Test
    public void manualAwayTest() {
        // TODO: test manualAway
    }

    /**
     * Test the property 'ok'
     */
    @Test
    public void okTest() {
        // TODO: test ok
    }

    /**
     * Test the property 'online'
     */
    @Test
    public void onlineTest() {
        // TODO: test online
    }

    /**
     * Test the property 'presence'
     */
    @Test
    public void presenceTest() {
        // TODO: test presence
    }

}
