/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DefsOkTrue;
import com.konfigthis.client.model.ObjsUserProfile;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UsersprofileSetProfileInfoResponse
 */
public class UsersprofileSetProfileInfoResponseTest {
    private final UsersprofileSetProfileInfoResponse model = new UsersprofileSetProfileInfoResponse();

    /**
     * Model tests for UsersprofileSetProfileInfoResponse
     */
    @Test
    public void testUsersprofileSetProfileInfoResponse() {
        // TODO: test UsersprofileSetProfileInfoResponse
    }

    /**
     * Test the property 'emailPending'
     */
    @Test
    public void emailPendingTest() {
        // TODO: test emailPending
    }

    /**
     * Test the property 'ok'
     */
    @Test
    public void okTest() {
        // TODO: test ok
    }

    /**
     * Test the property 'profile'
     */
    @Test
    public void profileTest() {
        // TODO: test profile
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

}
