/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest {
  public static final String SERIALIZED_NAME_DISCOVERABILITY = "discoverability";
  @SerializedName(SERIALIZED_NAME_DISCOVERABILITY)
  private String discoverability;

  public static final String SERIALIZED_NAME_TEAM_ID = "team_id";
  @SerializedName(SERIALIZED_NAME_TEAM_ID)
  private String teamId;

  public AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest() {
  }

  public AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest discoverability(String discoverability) {
    
    
    
    
    this.discoverability = discoverability;
    return this;
  }

   /**
   * This workspace&#39;s discovery setting. It must be set to one of &#x60;open&#x60;, &#x60;invite_only&#x60;, &#x60;closed&#x60;, or &#x60;unlisted&#x60;.
   * @return discoverability
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "This workspace's discovery setting. It must be set to one of `open`, `invite_only`, `closed`, or `unlisted`.")

  public String getDiscoverability() {
    return discoverability;
  }


  public void setDiscoverability(String discoverability) {
    
    
    
    this.discoverability = discoverability;
  }


  public AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest teamId(String teamId) {
    
    
    
    
    this.teamId = teamId;
    return this;
  }

   /**
   * The ID of the workspace to set discoverability on.
   * @return teamId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The ID of the workspace to set discoverability on.")

  public String getTeamId() {
    return teamId;
  }


  public void setTeamId(String teamId) {
    
    
    
    this.teamId = teamId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest instance itself
   */
  public AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest adminteamssettingsSetDiscoverabilityOfWorkspaceRequest = (AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest) o;
    return Objects.equals(this.discoverability, adminteamssettingsSetDiscoverabilityOfWorkspaceRequest.discoverability) &&
        Objects.equals(this.teamId, adminteamssettingsSetDiscoverabilityOfWorkspaceRequest.teamId)&&
        Objects.equals(this.additionalProperties, adminteamssettingsSetDiscoverabilityOfWorkspaceRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(discoverability, teamId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest {\n");
    sb.append("    discoverability: ").append(toIndentedString(discoverability)).append("\n");
    sb.append("    teamId: ").append(toIndentedString(teamId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("discoverability");
    openapiFields.add("team_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("discoverability");
    openapiRequiredFields.add("team_id");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest is not found in the empty JSON string", AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("discoverability").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `discoverability` to be a primitive type in the JSON string but got `%s`", jsonObj.get("discoverability").toString()));
      }
      if (!jsonObj.get("team_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `team_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("team_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest>() {
           @Override
           public void write(JsonWriter out, AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest
  * @throws IOException if the JSON string is invalid with respect to AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest
  */
  public static AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest.class);
  }

 /**
  * Convert an instance of AdminteamssettingsSetDiscoverabilityOfWorkspaceRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

