/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * UsergroupsusersUpdateListRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class UsergroupsusersUpdateListRequest {
  public static final String SERIALIZED_NAME_INCLUDE_COUNT = "include_count";
  @SerializedName(SERIALIZED_NAME_INCLUDE_COUNT)
  private Boolean includeCount;

  public static final String SERIALIZED_NAME_USERGROUP = "usergroup";
  @SerializedName(SERIALIZED_NAME_USERGROUP)
  private String usergroup;

  public static final String SERIALIZED_NAME_USERS = "users";
  @SerializedName(SERIALIZED_NAME_USERS)
  private String users;

  public UsergroupsusersUpdateListRequest() {
  }

  public UsergroupsusersUpdateListRequest includeCount(Boolean includeCount) {
    
    
    
    
    this.includeCount = includeCount;
    return this;
  }

   /**
   * Include the number of users in the User Group.
   * @return includeCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Include the number of users in the User Group.")

  public Boolean getIncludeCount() {
    return includeCount;
  }


  public void setIncludeCount(Boolean includeCount) {
    
    
    
    this.includeCount = includeCount;
  }


  public UsergroupsusersUpdateListRequest usergroup(String usergroup) {
    
    
    
    
    this.usergroup = usergroup;
    return this;
  }

   /**
   * The encoded ID of the User Group to update.
   * @return usergroup
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The encoded ID of the User Group to update.")

  public String getUsergroup() {
    return usergroup;
  }


  public void setUsergroup(String usergroup) {
    
    
    
    this.usergroup = usergroup;
  }


  public UsergroupsusersUpdateListRequest users(String users) {
    
    
    
    
    this.users = users;
    return this;
  }

   /**
   * A comma separated string of encoded user IDs that represent the entire list of users for the User Group.
   * @return users
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A comma separated string of encoded user IDs that represent the entire list of users for the User Group.")

  public String getUsers() {
    return users;
  }


  public void setUsers(String users) {
    
    
    
    this.users = users;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the UsergroupsusersUpdateListRequest instance itself
   */
  public UsergroupsusersUpdateListRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsergroupsusersUpdateListRequest usergroupsusersUpdateListRequest = (UsergroupsusersUpdateListRequest) o;
    return Objects.equals(this.includeCount, usergroupsusersUpdateListRequest.includeCount) &&
        Objects.equals(this.usergroup, usergroupsusersUpdateListRequest.usergroup) &&
        Objects.equals(this.users, usergroupsusersUpdateListRequest.users)&&
        Objects.equals(this.additionalProperties, usergroupsusersUpdateListRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(includeCount, usergroup, users, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsergroupsusersUpdateListRequest {\n");
    sb.append("    includeCount: ").append(toIndentedString(includeCount)).append("\n");
    sb.append("    usergroup: ").append(toIndentedString(usergroup)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("include_count");
    openapiFields.add("usergroup");
    openapiFields.add("users");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("usergroup");
    openapiRequiredFields.add("users");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UsergroupsusersUpdateListRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!UsergroupsusersUpdateListRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UsergroupsusersUpdateListRequest is not found in the empty JSON string", UsergroupsusersUpdateListRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UsergroupsusersUpdateListRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("usergroup").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `usergroup` to be a primitive type in the JSON string but got `%s`", jsonObj.get("usergroup").toString()));
      }
      if (!jsonObj.get("users").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `users` to be a primitive type in the JSON string but got `%s`", jsonObj.get("users").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UsergroupsusersUpdateListRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UsergroupsusersUpdateListRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UsergroupsusersUpdateListRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UsergroupsusersUpdateListRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UsergroupsusersUpdateListRequest>() {
           @Override
           public void write(JsonWriter out, UsergroupsusersUpdateListRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public UsergroupsusersUpdateListRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             UsergroupsusersUpdateListRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UsergroupsusersUpdateListRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UsergroupsusersUpdateListRequest
  * @throws IOException if the JSON string is invalid with respect to UsergroupsusersUpdateListRequest
  */
  public static UsergroupsusersUpdateListRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UsergroupsusersUpdateListRequest.class);
  }

 /**
  * Convert an instance of UsergroupsusersUpdateListRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

