openapi: 3.0.0
info:
  contact:
    name: Slack developer relations
    url: https://api.slack.com/support
  description: "One way to interact with the Slack platform is its HTTP RPC-based\
    \ Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace\
    \ tokens blessed with related OAuth scopes."
  title: Slack Web API
  version: 1.7.0
  x-apisguru-categories:
  - collaboration
  - messaging
  x-logo:
    url: http://static.tumblr.com/wvuzcz9/LlKncfhmp/slack_logo_240.png
  x-origin:
  - version: "3.0"
    format: openapi
    url: https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json
  x-providerName: slack.com
  x-konfig-ignore:
    object-with-no-properties: true
  x-konfig-has-globally-required-security: true
servers:
- url: https://slack.com/api
tags:
- name: admin
- name: conversations
- name: admin.conversations
- name: files
- name: users
- name: chat
- name: admin.users
- name: apps
- name: usergroups
- name: admin.teams.settings
- name: calls
- name: files.remote
- name: admin.emoji
- name: dnd
- name: reminders
- name: team
- name: admin.usergroups
- name: reactions
- name: views
- name: admin.conversations.restrictAccess
- name: admin.inviteRequests
- name: oauth
- name: pins
- name: stars
- name: workflows
- name: admin.apps
- name: admin.teams
- name: admin.users.session
- name: apps.permissions
- name: apps.permissions.users
- name: auth
- name: calls.participants
- name: usergroups.users
- name: users.profile
- name: admin.apps.approved
- name: admin.apps.requests
- name: admin.apps.restricted
- name: admin.conversations.ekm
- name: admin.inviteRequests.approved
- name: admin.inviteRequests.denied
- name: admin.teams.admins
- name: admin.teams.owners
- name: api
- name: apps.event.authorizations
- name: apps.permissions.resources
- name: apps.permissions.scopes
- name: bots
- name: chat.scheduledMessages
- name: dialog
- name: emoji
- name: files.comments
- name: migration
- name: oauth.v2
- name: rtm
- name: search
- name: team.profile
paths:
  /admin.apps.approve:
    post:
      description: Approve an app for installation on a workspace.
      operationId: Adminapps_approveAppInstallation
      security:
      - slackAuth:
        - admin.apps:write
      tags:
      - admin.apps
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.apps.approve
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.apps.approved.list:
    get:
      description: List approved apps for an org or workspace.
      operationId: Adminappsapproved_list
      security:
      - slackAuth:
        - admin.apps:read
      tags:
      - admin.apps.approved
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.apps.approved.list
      x-accepts: application/json
  /admin.apps.requests.list:
    get:
      description: List app requests for a team/workspace.
      operationId: Adminappsrequests_list
      security:
      - slackAuth:
        - admin.apps:read
      tags:
      - admin.apps.requests
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.apps.requests.list
      x-accepts: application/json
  /admin.apps.restrict:
    post:
      description: Restrict an app for installation on a workspace.
      operationId: Adminapps_restrictApp
      security:
      - slackAuth:
        - admin.apps:write
      tags:
      - admin.apps
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.apps.restrict
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.apps.restricted.list:
    get:
      description: List restricted apps for an org or workspace.
      operationId: Adminappsrestricted_getList
      security:
      - slackAuth:
        - admin.apps:read
      tags:
      - admin.apps.restricted
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.apps.restricted.list
      x-accepts: application/json
  /admin.conversations.archive:
    post:
      description: Archive a public or private channel.
      operationId: Adminconversations_archiveChannel
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.conversations.archive
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.conversations.convertToPrivate:
    post:
      description: Convert a public channel to a private channel.
      operationId: Adminconversations_convertToPrivateChannel
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.conversations.convertToPrivate
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.conversations.create:
    post:
      description: Create a public or private channel-based conversation.
      operationId: Adminconversations_createChannelBasedConversation
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.conversations.create
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.conversations.delete:
    post:
      description: Delete a public or private channel.
      operationId: Adminconversations_deleteChannel
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.conversations.delete
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.conversations.disconnectShared:
    post:
      description: Disconnect a connected channel from one or more workspaces.
      operationId: Adminconversations_disconnectSharedChannel
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.conversations.disconnectShared
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.conversations.ekm.listOriginalConnectedChannelInfo:
    get:
      description: "List all disconnected channels—i.e., channels that were once connected\
        \ to other workspaces and then disconnected—and the corresponding original\
        \ channel IDs for key revocation with EKM."
      operationId: Adminconversationsekm_listOriginalConnectedChannelInfo
      security:
      - slackAuth:
        - admin.conversations:read
      tags:
      - admin.conversations.ekm
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.conversations.ekm.listOriginalConnectedChannelInfo
      x-accepts: application/json
  /admin.conversations.getConversationPrefs:
    get:
      description: Get conversation preferences for a public or private channel.
      operationId: Adminconversations_getConversationPrefs
      security:
      - slackAuth:
        - admin.conversations:read
      tags:
      - admin.conversations
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.conversations.getConversationPrefs
      x-accepts: application/json
  /admin.conversations.getTeams:
    get:
      description: Get all the workspaces a given public or private channel is connected
        to within this Enterprise org.
      operationId: Adminconversations_getTeamsList
      security:
      - slackAuth:
        - admin.conversations:read
      tags:
      - admin.conversations
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.conversations.getTeams
      x-accepts: application/json
  /admin.conversations.invite:
    post:
      description: Invite a user to a public or private channel.
      operationId: Adminconversations_inviteUserToChannel
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.conversations.invite
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.conversations.rename:
    post:
      description: Rename a public or private channel.
      operationId: Adminconversations_renameChannel
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.conversations.rename
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.conversations.restrictAccess.addGroup:
    post:
      description: Add an allowlist of IDP groups for accessing a channel
      operationId: AdminconversationsrestrictAccess_addGroupIdpGroups
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations.restrictAccess
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.conversations.restrictAccess.addGroup
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.conversations.restrictAccess.listGroups:
    get:
      description: List all IDP Groups linked to a channel
      operationId: AdminconversationsrestrictAccess_listGroups
      security:
      - slackAuth:
        - admin.conversations:read
      tags:
      - admin.conversations.restrictAccess
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.conversations.restrictAccess.listGroups
      x-accepts: application/json
  /admin.conversations.restrictAccess.removeGroup:
    post:
      description: Remove a linked IDP group linked from a private channel
      operationId: AdminconversationsrestrictAccess_removeIdpGroup
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations.restrictAccess
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.conversations.restrictAccess.removeGroup
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.conversations.search:
    get:
      description: Search for public or private channels in an Enterprise organization.
      operationId: Adminconversations_searchChannels
      security:
      - slackAuth:
        - admin.conversations:read
      tags:
      - admin.conversations
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.conversations.search
      x-accepts: application/json
  /admin.conversations.setConversationPrefs:
    post:
      description: Set the posting permissions for a public or private channel.
      operationId: Adminconversations_setConversationPrefs
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.conversations.setConversationPrefs
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.conversations.setTeams:
    post:
      description: Set the workspaces in an Enterprise grid org that connect to a
        public or private channel.
      operationId: Adminconversations_setTeamsWorkspaceConnection
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.conversations.setTeams
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.conversations.unarchive:
    post:
      description: Unarchive a public or private channel.
      operationId: Adminconversations_unarchiveChannel
      security:
      - slackAuth:
        - admin.conversations:write
      tags:
      - admin.conversations
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.conversations.unarchive
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.emoji.add:
    post:
      description: Add an emoji.
      operationId: Adminemoji_addEmoji
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.emoji
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.emoji.add
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.emoji.addAlias:
    post:
      description: Add an emoji alias.
      operationId: Adminemoji_aliasAdd
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.emoji
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.emoji.addAlias
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.emoji.list:
    get:
      description: List emoji for an Enterprise Grid organization.
      operationId: Adminemoji_listEnterpriseEmoji
      security:
      - slackAuth:
        - admin.teams:read
      tags:
      - admin.emoji
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.emoji.list
      x-accepts: application/json
  /admin.emoji.remove:
    post:
      description: Remove an emoji across an Enterprise Grid organization
      operationId: Adminemoji_removeEnterpriseEmoji
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.emoji
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.emoji.remove
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.emoji.rename:
    post:
      description: Rename an emoji.
      operationId: Adminemoji_renameEmoji
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.emoji
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.emoji.rename
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.inviteRequests.approve:
    post:
      description: Approve a workspace invite request.
      operationId: AdmininviteRequests_approveRequest
      security:
      - slackAuth:
        - admin.invites:write
      tags:
      - admin.inviteRequests
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.inviteRequests.approve
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.inviteRequests.approved.list:
    get:
      description: List all approved workspace invite requests.
      operationId: AdmininviteRequestsapproved_list
      security:
      - slackAuth:
        - admin.invites:read
      tags:
      - admin.inviteRequests.approved
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.inviteRequests.approved.list
      x-accepts: application/json
  /admin.inviteRequests.denied.list:
    get:
      description: List all denied workspace invite requests.
      operationId: AdmininviteRequestsdenied_list
      security:
      - slackAuth:
        - admin.invites:read
      tags:
      - admin.inviteRequests.denied
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.inviteRequests.denied.list
      x-accepts: application/json
  /admin.inviteRequests.deny:
    post:
      description: Deny a workspace invite request.
      operationId: AdmininviteRequests_denyRequest
      security:
      - slackAuth:
        - admin.invites:write
      tags:
      - admin.inviteRequests
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.inviteRequests.deny
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.inviteRequests.list:
    get:
      description: List all pending workspace invite requests.
      operationId: AdmininviteRequests_listPendingWorkspaceInviteRequests
      security:
      - slackAuth:
        - admin.invites:read
      tags:
      - admin.inviteRequests
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.inviteRequests.list
      x-accepts: application/json
  /admin.teams.admins.list:
    get:
      description: List all of the admins on a given workspace.
      operationId: Adminteamsadmins_getAll
      security:
      - slackAuth:
        - admin.teams:read
      tags:
      - admin.teams.admins
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.teams.admins.list
      x-accepts: application/json
  /admin.teams.create:
    post:
      description: Create an Enterprise team.
      operationId: Adminteams_createEnterpriseTeam
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.teams
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.teams.create
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.teams.list:
    get:
      description: List all teams on an Enterprise organization
      operationId: Adminteams_listAll
      security:
      - slackAuth:
        - admin.teams:read
      tags:
      - admin.teams
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.teams.list
      x-accepts: application/json
  /admin.teams.owners.list:
    get:
      description: List all of the owners on a given workspace.
      operationId: Adminteamsowners_listOwners
      security:
      - slackAuth:
        - admin.teams:read
      tags:
      - admin.teams.owners
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.teams.owners.list
      x-accepts: application/json
  /admin.teams.settings.info:
    get:
      description: Fetch information about settings in a workspace
      operationId: Adminteamssettings_getInfo
      security:
      - slackAuth:
        - admin.teams:read
      tags:
      - admin.teams.settings
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.teams.settings.info
      x-accepts: application/json
  /admin.teams.settings.setDefaultChannels:
    post:
      description: Set the default channels of a workspace.
      operationId: Adminteamssettings_setDefaultChannels
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.teams.settings
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.teams.settings.setDefaultChannels
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.teams.settings.setDescription:
    post:
      description: Set the description of a given workspace.
      operationId: Adminteamssettings_setDescription
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.teams.settings
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.teams.settings.setDescription
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.teams.settings.setDiscoverability:
    post:
      description: An API method that allows admins to set the discoverability of
        a given workspace
      operationId: Adminteamssettings_setDiscoverabilityOfWorkspace
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.teams.settings
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.teams.settings.setDiscoverability
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.teams.settings.setIcon:
    post:
      description: Sets the icon of a workspace.
      operationId: Adminteamssettings_setIcon
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.teams.settings
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.teams.settings.setIcon
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.teams.settings.setName:
    post:
      description: Set the name of a given workspace.
      operationId: Adminteamssettings_setName
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.teams.settings
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.teams.settings.setName
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.usergroups.addChannels:
    post:
      description: Add one or more default channels to an IDP group.
      operationId: Adminusergroups_addDefaultChannels
      security:
      - slackAuth:
        - admin.usergroups:write
      tags:
      - admin.usergroups
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.usergroups.addChannels
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.usergroups.addTeams:
    post:
      description: Associate one or more default workspaces with an organization-wide
        IDP group.
      operationId: Adminusergroups_associateDefaultWorkspaces
      security:
      - slackAuth:
        - admin.teams:write
      tags:
      - admin.usergroups
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.usergroups.addTeams
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.usergroups.listChannels:
    get:
      description: List the channels linked to an org-level IDP group (user group).
      operationId: Adminusergroups_listChannelsGet
      security:
      - slackAuth:
        - admin.usergroups:read
      tags:
      - admin.usergroups
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.usergroups.listChannels
      x-accepts: application/json
  /admin.usergroups.removeChannels:
    post:
      description: Remove one or more default channels from an org-level IDP group
        (user group).
      operationId: Adminusergroups_removeChannels
      security:
      - slackAuth:
        - admin.usergroups:write
      tags:
      - admin.usergroups
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.usergroups.removeChannels
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.users.assign:
    post:
      description: Add an Enterprise user to a workspace.
      operationId: Adminusers_addWorkspaceUser
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.users.assign
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.users.invite:
    post:
      description: Invite a user to a workspace.
      operationId: Adminusers_inviteUserToWorkspace
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.users.invite
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.users.list:
    get:
      description: List users on a workspace
      operationId: Adminusers_listWorkspaceUsers
      security:
      - slackAuth:
        - admin.users:read
      tags:
      - admin.users
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--admin.users.list
      x-accepts: application/json
  /admin.users.remove:
    post:
      description: Remove a user from a workspace.
      operationId: Adminusers_removeUserFromWorkspace
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.users.remove
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.users.session.invalidate:
    post:
      description: Invalidate a single session for a user by session_id
      operationId: Adminuserssession_invalidateSession
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users.session
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.users.session.invalidate
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.users.session.reset:
    post:
      description: Wipes all valid sessions on all devices for a given user
      operationId: Adminuserssession_resetSessions
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users.session
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.users.session.reset
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.users.setAdmin:
    post:
      description: "Set an existing guest, regular user, or owner to be an admin user."
      operationId: Adminusers_setAdminUser
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.users.setAdmin
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.users.setExpiration:
    post:
      description: Set an expiration for a guest user
      operationId: Adminusers_setExpirationGuest
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.users.setExpiration
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.users.setOwner:
    post:
      description: "Set an existing guest, regular user, or admin user to be a workspace\
        \ owner."
      operationId: Adminusers_setWorkspaceOwner
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.users.setOwner
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /admin.users.setRegular:
    post:
      description: "Set an existing guest user, admin user, or owner to be a regular\
        \ user."
      operationId: Adminusers_setRegularUser
      security:
      - slackAuth:
        - admin.users:write
      tags:
      - admin.users
      - admin
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--admin.users.setRegular
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /api.test:
    get:
      description: Checks API calling code.
      operationId: api_test
      security:
      - slackAuth:
        - none
      tags:
      - api
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--api.test
      x-accepts: application/json
  /apps.event.authorizations.list:
    get:
      description: Get a list of authorizations for the given event context. Each
        authorization represents an app installation that the event is visible to.
      operationId: Appseventauthorizations_getList
      security:
      - slackAuth:
        - authorizations:read
      tags:
      - apps.event.authorizations
      - apps
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--apps.event.authorizations.list
      x-accepts: application/json
  /apps.permissions.info:
    get:
      description: Returns list of permissions this app has on a team.
      operationId: Appspermissions_listPermissions
      security:
      - slackAuth:
        - none
      tags:
      - apps.permissions
      - apps
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--apps.permissions.info
      x-accepts: application/json
  /apps.permissions.request:
    get:
      description: Allows an app to request additional scopes
      operationId: Appspermissions_additionalScopesRequest
      security:
      - slackAuth:
        - none
      tags:
      - apps.permissions
      - apps
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--apps.permissions.request
      x-accepts: application/json
  /apps.permissions.resources.list:
    get:
      description: Returns list of resource grants this app has on a team.
      operationId: Appspermissionsresources_getResourcesList
      security:
      - slackAuth:
        - none
      tags:
      - apps.permissions.resources
      - apps
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--apps.permissions.resources.list
      x-accepts: application/json
  /apps.permissions.scopes.list:
    get:
      description: Returns list of scopes this app has on a team.
      operationId: Appspermissionsscopes_getList
      security:
      - slackAuth:
        - none
      tags:
      - apps.permissions.scopes
      - apps
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--apps.permissions.scopes.list
      x-accepts: application/json
  /apps.permissions.users.list:
    get:
      description: Returns list of user grants and corresponding scopes this app has
        on a team.
      operationId: Appspermissionsusers_listUserGrants
      security:
      - slackAuth:
        - none
      tags:
      - apps.permissions.users
      - apps
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--apps.permissions.users.list
      x-accepts: application/json
  /apps.permissions.users.request:
    get:
      description: Enables an app to trigger a permissions modal to grant an app access
        to a user access scope.
      operationId: Appspermissionsusers_requestModal
      security:
      - slackAuth:
        - none
      tags:
      - apps.permissions.users
      - apps
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--apps.permissions.users.request
      x-accepts: application/json
  /apps.uninstall:
    get:
      description: Uninstalls your app from a workspace.
      operationId: apps_uninstall
      security:
      - slackAuth:
        - none
      tags:
      - apps
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--apps.uninstall
      x-accepts: application/json
  /auth.revoke:
    get:
      description: Revokes a token.
      operationId: auth_revoke
      security:
      - slackAuth:
        - none
      tags:
      - auth
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--auth.revoke
      x-accepts: application/json
  /auth.test:
    get:
      description: Checks authentication & identity.
      operationId: auth_test
      security:
      - slackAuth:
        - none
      tags:
      - auth
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--auth.test
      x-accepts: application/json
  /bots.info:
    get:
      description: Gets information about a bot user.
      operationId: bots_info
      security:
      - slackAuth:
        - users:read
      tags:
      - bots
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--bots.info
      x-accepts: application/json
  /calls.add:
    post:
      description: Registers a new Call.
      operationId: calls_add
      security:
      - slackAuth:
        - calls:write
      tags:
      - calls
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--calls.add
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /calls.end:
    post:
      description: Ends a Call.
      operationId: calls_end
      security:
      - slackAuth:
        - calls:write
      tags:
      - calls
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--calls.end
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /calls.info:
    get:
      description: Returns information about a Call.
      operationId: calls_info
      security:
      - slackAuth:
        - calls:read
      tags:
      - calls
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--calls.info
      x-accepts: application/json
  /calls.participants.add:
    post:
      description: Registers new participants added to a Call.
      operationId: Callsparticipants_addNewParticipant
      security:
      - slackAuth:
        - calls:write
      tags:
      - calls.participants
      - calls
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--calls.participants.add
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /calls.participants.remove:
    post:
      description: Registers participants removed from a Call.
      operationId: Callsparticipants_registerRemoved
      security:
      - slackAuth:
        - calls:write
      tags:
      - calls.participants
      - calls
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--calls.participants.remove
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /calls.update:
    post:
      description: Updates information about a Call.
      operationId: calls_update
      security:
      - slackAuth:
        - calls:write
      tags:
      - calls
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--calls.update
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /chat.delete:
    post:
      description: Deletes a message.
      operationId: chat_delete
      security:
      - slackAuth:
        - chat:write:user
        - chat:write:bot
      tags:
      - chat
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--chat.delete
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /chat.deleteScheduledMessage:
    post:
      description: Deletes a pending scheduled message from the queue.
      operationId: chat_deleteScheduledMessage
      security:
      - slackAuth:
        - chat:write:user
        - chat:write:bot
      tags:
      - chat
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--chat.deleteScheduledMessage
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /chat.getPermalink:
    get:
      description: Retrieve a permalink URL for a specific extant message
      operationId: chat_getPermalink
      security:
      - slackAuth:
        - none
      tags:
      - chat
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--chat.getPermalink
      x-accepts: application/json
  /chat.meMessage:
    post:
      description: Share a me message into a channel.
      operationId: chat_meMessage
      security:
      - slackAuth:
        - chat:write:user
        - chat:write:bot
      tags:
      - chat
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--chat.meMessage
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /chat.postEphemeral:
    post:
      description: Sends an ephemeral message to a user in a channel.
      operationId: chat_postEphemeral
      security:
      - slackAuth:
        - chat:write:user
        - chat:write:bot
      tags:
      - chat
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--chat.postEphemeral
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /chat.postMessage:
    post:
      description: Sends a message to a channel.
      operationId: chat_postMessage
      security:
      - slackAuth:
        - chat:write:user
        - chat:write:bot
      tags:
      - chat
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--chat.postMessage
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /chat.scheduleMessage:
    post:
      description: Schedules a message to be sent to a channel.
      operationId: chat_scheduleMessage
      security:
      - slackAuth:
        - chat:write:user
        - chat:write:bot
      tags:
      - chat
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--chat.scheduleMessage
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /chat.scheduledMessages.list:
    get:
      description: Returns a list of scheduled messages.
      operationId: ChatscheduledMessages_list
      security:
      - slackAuth:
        - none
      tags:
      - chat.scheduledMessages
      - chat
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--chat.scheduledMessages.list
      x-accepts: application/json
  /chat.unfurl:
    post:
      description: Provide custom unfurl behavior for user-posted URLs
      operationId: chat_unfurl
      security:
      - slackAuth:
        - links:write
      tags:
      - chat
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--chat.unfurl
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /chat.update:
    post:
      description: Updates a message.
      operationId: chat_update
      security:
      - slackAuth:
        - chat:write:user
        - chat:write:bot
      tags:
      - chat
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--chat.update
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /conversations.archive:
    post:
      description: Archives a conversation.
      operationId: conversations_archive
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--conversations.archive
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /conversations.close:
    post:
      description: Closes a direct message or multi-person direct message.
      operationId: conversations_close
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--conversations.close
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /conversations.create:
    post:
      description: Initiates a public or private channel-based conversation
      operationId: conversations_create
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--conversations.create
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /conversations.history:
    get:
      description: Fetches a conversation's history of messages and events.
      operationId: conversations_history
      security:
      - slackAuth:
        - channels:history
        - groups:history
        - im:history
        - mpim:history
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--conversations.history
      x-accepts: application/json
  /conversations.info:
    get:
      description: Retrieve information about a conversation.
      operationId: conversations_info
      security:
      - slackAuth:
        - channels:read
        - groups:read
        - im:read
        - mpim:read
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--conversations.info
      x-accepts: application/json
  /conversations.invite:
    post:
      description: Invites users to a channel.
      operationId: conversations_invite
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--conversations.invite
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /conversations.join:
    post:
      description: Joins an existing conversation.
      operationId: conversations_join
      security:
      - slackAuth:
        - channels:write
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--conversations.join
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /conversations.kick:
    post:
      description: Removes a user from a conversation.
      operationId: conversations_kick
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--conversations.kick
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /conversations.leave:
    post:
      description: Leaves a conversation.
      operationId: conversations_leave
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--conversations.leave
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /conversations.list:
    get:
      description: Lists all channels in a Slack team.
      operationId: conversations_list
      security:
      - slackAuth:
        - channels:read
        - groups:read
        - im:read
        - mpim:read
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--conversations.list
      x-accepts: application/json
  /conversations.mark:
    post:
      description: Sets the read cursor in a channel.
      operationId: conversations_mark
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--conversations.mark
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /conversations.members:
    get:
      description: Retrieve members of a conversation.
      operationId: conversations_members
      security:
      - slackAuth:
        - channels:read
        - groups:read
        - im:read
        - mpim:read
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--conversations.members
      x-accepts: application/json
  /conversations.open:
    post:
      description: Opens or resumes a direct message or multi-person direct message.
      operationId: conversations_open
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--conversations.open
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /conversations.rename:
    post:
      description: Renames a conversation.
      operationId: conversations_rename
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--conversations.rename
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /conversations.replies:
    get:
      description: Retrieve a thread of messages posted to a conversation
      operationId: conversations_replies
      security:
      - slackAuth:
        - channels:history
        - groups:history
        - im:history
        - mpim:history
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--conversations.replies
      x-accepts: application/json
  /conversations.setPurpose:
    post:
      description: Sets the purpose for a conversation.
      operationId: conversations_setPurpose
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--conversations.setPurpose
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /conversations.setTopic:
    post:
      description: Sets the topic for a conversation.
      operationId: conversations_setTopic
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--conversations.setTopic
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /conversations.unarchive:
    post:
      description: Reverses conversation archival.
      operationId: conversations_unarchive
      security:
      - slackAuth:
        - channels:write
        - groups:write
        - im:write
        - mpim:write
      tags:
      - conversations
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--conversations.unarchive
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /dialog.open:
    get:
      description: Open a dialog with a user
      operationId: dialog_open
      security:
      - slackAuth:
        - none
      tags:
      - dialog
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--dialog.open
      x-accepts: application/json
  /dnd.endDnd:
    post:
      description: Ends the current user's Do Not Disturb session immediately.
      operationId: dnd_endDnd
      security:
      - slackAuth:
        - dnd:write
      tags:
      - dnd
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--dnd.endDnd
      x-accepts: application/json
  /dnd.endSnooze:
    post:
      description: Ends the current user's snooze mode immediately.
      operationId: dnd_endSnooze
      security:
      - slackAuth:
        - dnd:write
      tags:
      - dnd
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--dnd.endSnooze
      x-accepts: application/json
  /dnd.info:
    get:
      description: Retrieves a user's current Do Not Disturb status.
      operationId: dnd_info
      security:
      - slackAuth:
        - dnd:read
      tags:
      - dnd
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--dnd.info
      x-accepts: application/json
  /dnd.setSnooze:
    post:
      description: "Turns on Do Not Disturb mode for the current user, or changes\
        \ its duration."
      operationId: dnd_setSnooze
      security:
      - slackAuth:
        - dnd:write
      tags:
      - dnd
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--dnd.setSnooze
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /dnd.teamInfo:
    get:
      description: Retrieves the Do Not Disturb status for up to 50 users on a team.
      operationId: dnd_teamInfo
      security:
      - slackAuth:
        - dnd:read
      tags:
      - dnd
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--dnd.teamInfo
      x-accepts: application/json
  /emoji.list:
    get:
      description: Lists custom emoji for a team.
      operationId: emoji_list
      security:
      - slackAuth:
        - emoji:read
      tags:
      - emoji
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--emoji.list
      x-accepts: application/json
  /files.comments.delete:
    post:
      description: Deletes an existing comment on a file.
      operationId: Filescomments_deleteComment
      security:
      - slackAuth:
        - files:write:user
      tags:
      - files.comments
      - files
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--files.comments.delete
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /files.delete:
    post:
      description: Deletes a file.
      operationId: files_delete
      security:
      - slackAuth:
        - files:write:user
      tags:
      - files
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--files.delete
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /files.info:
    get:
      description: Gets information about a file.
      operationId: files_info
      security:
      - slackAuth:
        - files:read
      tags:
      - files
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--files.info
      x-accepts: application/json
  /files.list:
    get:
      description: "List for a team, in a channel, or from a user with applied filters."
      operationId: files_list
      security:
      - slackAuth:
        - files:read
      tags:
      - files
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--files.list
      x-accepts: application/json
  /files.remote.add:
    post:
      description: Adds a file from a remote service
      operationId: Filesremote_addFromRemote
      security:
      - slackAuth:
        - remote_files:write
      tags:
      - files.remote
      - files
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--files.remote.add
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /files.remote.info:
    get:
      description: Retrieve information about a remote file added to Slack
      operationId: Filesremote_getInfo
      security:
      - slackAuth:
        - remote_files:read
      tags:
      - files.remote
      - files
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--files.remote.info
      x-accepts: application/json
  /files.remote.list:
    get:
      description: Retrieve information about a remote file added to Slack
      operationId: Filesremote_listRemoteFiles
      security:
      - slackAuth:
        - remote_files:read
      tags:
      - files.remote
      - files
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--files.remote.list
      x-accepts: application/json
  /files.remote.remove:
    post:
      description: Remove a remote file.
      operationId: Filesremote_deleteFile
      security:
      - slackAuth:
        - remote_files:write
      tags:
      - files.remote
      - files
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--files.remote.remove
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /files.remote.share:
    get:
      description: Share a remote file into a channel.
      operationId: Filesremote_shareRemoteFile
      security:
      - slackAuth:
        - remote_files:share
      tags:
      - files.remote
      - files
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--files.remote.share
      x-accepts: application/json
  /files.remote.update:
    post:
      description: Updates an existing remote file.
      operationId: Filesremote_updateRemoteFile
      security:
      - slackAuth:
        - remote_files:write
      tags:
      - files.remote
      - files
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--files.remote.update
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /files.revokePublicURL:
    post:
      description: Revokes public/external sharing access for a file
      operationId: files_revokePublicURL
      security:
      - slackAuth:
        - files:write:user
      tags:
      - files
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--files.revokePublicURL
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /files.sharedPublicURL:
    post:
      description: Enables a file for public/external sharing.
      operationId: files_sharedPublicURL
      security:
      - slackAuth:
        - files:write:user
      tags:
      - files
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--files.sharedPublicURL
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /files.upload:
    post:
      description: Uploads or creates a file.
      operationId: files_upload
      security:
      - slackAuth:
        - files:write:user
      tags:
      - files
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--files.upload
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /migration.exchange:
    get:
      description: "For Enterprise Grid workspaces, map local user IDs to global user\
        \ IDs"
      operationId: migration_exchange
      security:
      - slackAuth:
        - tokens.basic
      tags:
      - migration
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--migration.exchange
      x-accepts: application/json
  /oauth.access:
    get:
      description: Exchanges a temporary OAuth verifier code for an access token.
      operationId: oauth_access
      security:
      - slackAuth:
        - none
      tags:
      - oauth
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--oauth.access
      x-accepts: application/json
  /oauth.token:
    get:
      description: Exchanges a temporary OAuth verifier code for a workspace token.
      operationId: oauth_token
      security:
      - slackAuth:
        - none
      tags:
      - oauth
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--oauth.token
      x-accepts: application/json
  /oauth.v2.access:
    get:
      description: Exchanges a temporary OAuth verifier code for an access token.
      operationId: Oauthv2_exchangeToken
      security:
      - slackAuth:
        - none
      tags:
      - oauth.v2
      - oauth
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--oauth.v2.access
      x-accepts: application/json
  /pins.add:
    post:
      description: Pins an item to a channel.
      operationId: pins_add
      security:
      - slackAuth:
        - pins:write
      tags:
      - pins
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--pins.add
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /pins.list:
    get:
      description: Lists items pinned to a channel.
      operationId: pins_list
      security:
      - slackAuth:
        - pins:read
      tags:
      - pins
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--pins.list
      x-accepts: application/json
  /pins.remove:
    post:
      description: Un-pins an item from a channel.
      operationId: pins_remove
      security:
      - slackAuth:
        - pins:write
      tags:
      - pins
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--pins.remove
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /reactions.add:
    post:
      description: Adds a reaction to an item.
      operationId: reactions_add
      security:
      - slackAuth:
        - reactions:write
      tags:
      - reactions
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--reactions.add
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /reactions.get:
    get:
      description: Gets reactions for an item.
      operationId: reactions_get
      security:
      - slackAuth:
        - reactions:read
      tags:
      - reactions
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--reactions.get
      x-accepts: application/json
  /reactions.list:
    get:
      description: Lists reactions made by a user.
      operationId: reactions_list
      security:
      - slackAuth:
        - reactions:read
      tags:
      - reactions
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--reactions.list
      x-accepts: application/json
  /reactions.remove:
    post:
      description: Removes a reaction from an item.
      operationId: reactions_remove
      security:
      - slackAuth:
        - reactions:write
      tags:
      - reactions
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--reactions.remove
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /reminders.add:
    post:
      description: Creates a reminder.
      operationId: reminders_add
      security:
      - slackAuth:
        - reminders:write
      tags:
      - reminders
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--reminders.add
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /reminders.complete:
    post:
      description: Marks a reminder as complete.
      operationId: reminders_complete
      security:
      - slackAuth:
        - reminders:write
      tags:
      - reminders
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--reminders.complete
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /reminders.delete:
    post:
      description: Deletes a reminder.
      operationId: reminders_delete
      security:
      - slackAuth:
        - reminders:write
      tags:
      - reminders
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--reminders.delete
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /reminders.info:
    get:
      description: Gets information about a reminder.
      operationId: reminders_info
      security:
      - slackAuth:
        - reminders:read
      tags:
      - reminders
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--reminders.info
      x-accepts: application/json
  /reminders.list:
    get:
      description: Lists all reminders created by or for a given user.
      operationId: reminders_list
      security:
      - slackAuth:
        - reminders:read
      tags:
      - reminders
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--reminders.list
      x-accepts: application/json
  /rtm.connect:
    get:
      description: Starts a Real Time Messaging session.
      operationId: rtm_connect
      security:
      - slackAuth:
        - rtm:stream
      tags:
      - rtm
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--rtm.connect
      x-accepts: application/json
  /search.messages:
    get:
      description: Searches for messages matching a query.
      operationId: search_messages
      security:
      - slackAuth:
        - search:read
      tags:
      - search
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--search.messages
      x-accepts: application/json
  /stars.add:
    post:
      description: Adds a star to an item.
      operationId: stars_add
      security:
      - slackAuth:
        - stars:write
      tags:
      - stars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--stars.add
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /stars.list:
    get:
      description: Lists stars for a user.
      operationId: stars_list
      security:
      - slackAuth:
        - stars:read
      tags:
      - stars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--stars.list
      x-accepts: application/json
  /stars.remove:
    post:
      description: Removes a star from an item.
      operationId: stars_remove
      security:
      - slackAuth:
        - stars:write
      tags:
      - stars
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--stars.remove
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /team.accessLogs:
    get:
      description: Gets the access logs for the current team.
      operationId: team_accessLogs
      security:
      - slackAuth:
        - admin
      tags:
      - team
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--team.accessLogs
      x-accepts: application/json
  /team.billableInfo:
    get:
      description: Gets billable users information for the current team.
      operationId: team_billableInfo
      security:
      - slackAuth:
        - admin
      tags:
      - team
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--team.billableInfo
      x-accepts: application/json
  /team.info:
    get:
      description: Gets information about the current team.
      operationId: team_info
      security:
      - slackAuth:
        - team:read
      tags:
      - team
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--team.info
      x-accepts: application/json
  /team.integrationLogs:
    get:
      description: Gets the integration logs for the current team.
      operationId: team_integrationLogs
      security:
      - slackAuth:
        - admin
      tags:
      - team
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--team.integrationLogs
      x-accepts: application/json
  /team.profile.get:
    get:
      description: Retrieve a team's profile.
      operationId: Teamprofile_getProfile
      security:
      - slackAuth:
        - users.profile:read
      tags:
      - team.profile
      - team
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--team.profile.get
      x-accepts: application/json
  /usergroups.create:
    post:
      description: Create a User Group
      operationId: usergroups_create
      security:
      - slackAuth:
        - usergroups:write
      tags:
      - usergroups
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--usergroups.create
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /usergroups.disable:
    post:
      description: Disable an existing User Group
      operationId: usergroups_disable
      security:
      - slackAuth:
        - usergroups:write
      tags:
      - usergroups
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--usergroups.disable
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /usergroups.enable:
    post:
      description: Enable a User Group
      operationId: usergroups_enable
      security:
      - slackAuth:
        - usergroups:write
      tags:
      - usergroups
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--usergroups.enable
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /usergroups.list:
    get:
      description: List all User Groups for a team
      operationId: usergroups_list
      security:
      - slackAuth:
        - usergroups:read
      tags:
      - usergroups
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--usergroups.list
      x-accepts: application/json
  /usergroups.update:
    post:
      description: Update an existing User Group
      operationId: usergroups_update
      security:
      - slackAuth:
        - usergroups:write
      tags:
      - usergroups
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--usergroups.update
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /usergroups.users.list:
    get:
      description: List all users in a User Group
      operationId: Usergroupsusers_listAllUsers
      security:
      - slackAuth:
        - usergroups:read
      tags:
      - usergroups.users
      - usergroups
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--usergroups.users.list
      x-accepts: application/json
  /usergroups.users.update:
    post:
      description: Update the list of users for a User Group
      operationId: Usergroupsusers_updateList
      security:
      - slackAuth:
        - usergroups:write
      tags:
      - usergroups.users
      - usergroups
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--usergroups.users.update
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /users.conversations:
    get:
      description: List conversations the calling user may access.
      operationId: users_conversations
      security:
      - slackAuth:
        - channels:read
        - groups:read
        - im:read
        - mpim:read
      tags:
      - users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users.conversations
      x-accepts: application/json
  /users.deletePhoto:
    post:
      description: Delete the user profile photo
      operationId: users_deletePhoto
      security:
      - slackAuth:
        - users.profile:write
      tags:
      - users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--users.deletePhoto
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /users.getPresence:
    get:
      description: Gets user presence information.
      operationId: users_getPresence
      security:
      - slackAuth:
        - users:read
      tags:
      - users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users.getPresence
      x-accepts: application/json
  /users.identity:
    get:
      description: Get a user's identity.
      operationId: users_identity
      security:
      - slackAuth:
        - identity.basic
      tags:
      - users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users.identity
      x-accepts: application/json
  /users.info:
    get:
      description: Gets information about a user.
      operationId: users_info
      security:
      - slackAuth:
        - users:read
      tags:
      - users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users.info
      x-accepts: application/json
  /users.list:
    get:
      description: Lists all users in a Slack team.
      operationId: users_list
      security:
      - slackAuth:
        - users:read
      tags:
      - users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users.list
      x-accepts: application/json
  /users.lookupByEmail:
    get:
      description: Find a user with an email address.
      operationId: users_lookupByEmail
      security:
      - slackAuth:
        - users:read.email
      tags:
      - users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users.lookupByEmail
      x-accepts: application/json
  /users.profile.get:
    get:
      description: Retrieves a user's profile information.
      operationId: Usersprofile_getProfileInfo
      security:
      - slackAuth:
        - users.profile:read
      tags:
      - users.profile
      - users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--users.profile.get
      x-accepts: application/json
  /users.profile.set:
    post:
      description: Set the profile information for a user.
      operationId: Usersprofile_setProfileInfo
      security:
      - slackAuth:
        - users.profile:write
      tags:
      - users.profile
      - users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--users.profile.set
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /users.setActive:
    post:
      description: Marked a user as active. Deprecated and non-functional.
      operationId: users_setActive
      security:
      - slackAuth:
        - users:write
      tags:
      - users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--users.setActive
      x-accepts: application/json
  /users.setPhoto:
    post:
      description: Set the user profile photo
      operationId: users_setPhoto
      security:
      - slackAuth:
        - users.profile:write
      tags:
      - users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--users.setPhoto
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /users.setPresence:
    post:
      description: Manually sets user presence.
      operationId: users_setPresence
      security:
      - slackAuth:
        - users:write
      tags:
      - users
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-post--users.setPresence
      x-content-type: application/x-www-form-urlencoded
      x-accepts: application/json
  /views.open:
    get:
      description: Open a view for a user.
      operationId: views_open
      security:
      - slackAuth:
        - none
      tags:
      - views
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--views.open
      x-accepts: application/json
  /views.publish:
    get:
      description: Publish a static view for a User.
      operationId: views_publish
      security:
      - slackAuth:
        - none
      tags:
      - views
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--views.publish
      x-accepts: application/json
  /views.push:
    get:
      description: Push a view onto the stack of a root view.
      operationId: views_push
      security:
      - slackAuth:
        - none
      tags:
      - views
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--views.push
      x-accepts: application/json
  /views.update:
    get:
      description: Update an existing view.
      operationId: views_update
      security:
      - slackAuth:
        - none
      tags:
      - views
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--views.update
      x-accepts: application/json
  /workflows.stepCompleted:
    get:
      description: Indicate that an app's step in a workflow completed execution.
      operationId: workflows_stepCompleted
      security:
      - slackAuth:
        - workflow.steps:execute
      tags:
      - workflows
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--workflows.stepCompleted
      x-accepts: application/json
  /workflows.stepFailed:
    get:
      description: Indicate that an app's step in a workflow failed to execute.
      operationId: workflows_stepFailed
      security:
      - slackAuth:
        - workflow.steps:execute
      tags:
      - workflows
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--workflows.stepFailed
      x-accepts: application/json
  /workflows.updateStep:
    get:
      description: Update the configuration for a workflow extension step.
      operationId: workflows_updateStep
      security:
      - slackAuth:
        - workflow.steps:execute
      tags:
      - workflows
      x-konfig-operation-can-have-single-parameter: true
      x-konfig-single-parameter-schema: konfig-generated-schema-single-parameter-schema-get--workflows.updateStep
      x-accepts: application/json
components:
  securitySchemes:
    slackAuth:
      flows:
        authorizationCode:
          authorizationUrl: https://slack.com/oauth/authorize
          scopes:
            admin: admin
            admin.apps:read: admin.apps:read
            admin.apps:write: admin.apps:write
            admin.conversations:read: admin.conversations:read
            admin.conversations:write: admin.conversations:write
            admin.invites:read: admin.invites:read
            admin.invites:write: admin.invites:write
            admin.teams:read: admin.teams:read
            admin.teams:write: admin.teams:write
            admin.usergroups:read: admin.usergroups:read
            admin.usergroups:write: admin.usergroups:write
            admin.users:read: admin.users:read
            admin.users:write: admin.users:write
            authorizations:read: authorizations:read
            bot: Bot user scope
            calls:read: calls:read
            calls:write: calls:write
            channels:history: channels:history
            channels:manage: channels:manage
            channels:read: channels:read
            channels:write: channels:write
            chat:write: chat:write
            chat:write:bot: Author messages as a bot
            chat:write:user: Author messages as a user
            conversations:history: conversations:history
            conversations:read: conversations:read
            conversations:write: conversations:write
            dnd:read: dnd:read
            dnd:write: dnd:write
            emoji:read: emoji:read
            files:read: files:read
            files:write:user: files:write:user
            groups:history: groups:history
            groups:read: groups:read
            groups:write: groups:write
            identity.basic: identity.basic
            im:history: im:history
            im:read: im:read
            im:write: im:write
            links:write: links:write
            mpim:history: mpim:history
            mpim:read: mpim:read
            mpim:write: mpim:write
            none: No scope required
            pins:read: pins:read
            pins:write: pins:write
            reactions:read: reactions:read
            reactions:write: reactions:write
            reminders:read: reminders:read
            reminders:write: reminders:write
            remote_files:read: remote_files:read
            remote_files:share: remote_files:share
            remote_files:write: remote_files:write
            rtm:stream: rtm:stream
            search:read: search:read
            stars:read: stars:read
            stars:write: stars:write
            team:read: team:read
            tokens.basic: tokens.basic
            usergroups:read: usergroups:read
            usergroups:write: usergroups:write
            users.profile:read: users.profile:read
            users.profile:write: users.profile:write
            users:read: users:read
            users:read.email: users:read.email
            users:write: users:write
            workflow.steps:execute: workflow.steps:execute
          tokenUrl: https://slack.com/api/oauth.access
      type: oauth2
      x-konfig-globally-required-security: true

