/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.AppspermissionsAdditionalScopesRequestResponse;
import com.konfigthis.client.model.AppspermissionsAdditionalScopesRequestdefaultResponse;
import com.konfigthis.client.model.AppspermissionsListPermissionsResponse;
import com.konfigthis.client.model.AppspermissionsListPermissionsdefaultResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class AppsPermissionsApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AppsPermissionsApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public AppsPermissionsApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call additionalScopesRequestCall(String token, String scopes, String triggerId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/apps.permissions.request";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (token != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("token", token));
        }

        if (scopes != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("scopes", scopes));
        }

        if (triggerId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("trigger_id", triggerId));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "slackAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call additionalScopesRequestValidateBeforeCall(String token, String scopes, String triggerId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling additionalScopesRequest(Async)");
        }

        // verify the required parameter 'scopes' is set
        if (scopes == null) {
            throw new ApiException("Missing the required parameter 'scopes' when calling additionalScopesRequest(Async)");
        }

        // verify the required parameter 'triggerId' is set
        if (triggerId == null) {
            throw new ApiException("Missing the required parameter 'triggerId' when calling additionalScopesRequest(Async)");
        }

        return additionalScopesRequestCall(token, scopes, triggerId, _callback);

    }


    private ApiResponse<AppspermissionsAdditionalScopesRequestResponse> additionalScopesRequestWithHttpInfo(String token, String scopes, String triggerId) throws ApiException {
        okhttp3.Call localVarCall = additionalScopesRequestValidateBeforeCall(token, scopes, triggerId, null);
        Type localVarReturnType = new TypeToken<AppspermissionsAdditionalScopesRequestResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call additionalScopesRequestAsync(String token, String scopes, String triggerId, final ApiCallback<AppspermissionsAdditionalScopesRequestResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = additionalScopesRequestValidateBeforeCall(token, scopes, triggerId, _callback);
        Type localVarReturnType = new TypeToken<AppspermissionsAdditionalScopesRequestResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class AdditionalScopesRequestRequestBuilder {
        private final String token;
        private final String scopes;
        private final String triggerId;

        private AdditionalScopesRequestRequestBuilder(String token, String scopes, String triggerId) {
            this.token = token;
            this.scopes = scopes;
            this.triggerId = triggerId;
        }

        /**
         * Build call for additionalScopesRequest
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when trigger_id is invalid </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return additionalScopesRequestCall(token, scopes, triggerId, _callback);
        }


        /**
         * Execute additionalScopesRequest request
         * @return AppspermissionsAdditionalScopesRequestResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when trigger_id is invalid </td><td>  -  </td></tr>
         </table>
         */
        public AppspermissionsAdditionalScopesRequestResponse execute() throws ApiException {
            ApiResponse<AppspermissionsAdditionalScopesRequestResponse> localVarResp = additionalScopesRequestWithHttpInfo(token, scopes, triggerId);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute additionalScopesRequest request with HTTP info returned
         * @return ApiResponse&lt;AppspermissionsAdditionalScopesRequestResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when trigger_id is invalid </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<AppspermissionsAdditionalScopesRequestResponse> executeWithHttpInfo() throws ApiException {
            return additionalScopesRequestWithHttpInfo(token, scopes, triggerId);
        }

        /**
         * Execute additionalScopesRequest request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when trigger_id is invalid </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<AppspermissionsAdditionalScopesRequestResponse> _callback) throws ApiException {
            return additionalScopesRequestAsync(token, scopes, triggerId, _callback);
        }
    }

    /**
     * 
     * Allows an app to request additional scopes
     * @param token Authentication token. Requires scope: &#x60;none&#x60; (required)
     * @param scopes A comma separated list of scopes to request for (required)
     * @param triggerId Token used to trigger the permissions API (required)
     * @return AdditionalScopesRequestRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Standard failure response when trigger_id is invalid </td><td>  -  </td></tr>
     </table>
     * API method documentation
     * @see <a href="https://api.slack.com/methods/apps.permissions.request"> Documentation</a>
     */
    public AdditionalScopesRequestRequestBuilder additionalScopesRequest(String token, String scopes, String triggerId) throws IllegalArgumentException {
        if (token == null) throw new IllegalArgumentException("\"token\" is required but got null");
            

        if (scopes == null) throw new IllegalArgumentException("\"scopes\" is required but got null");
            

        if (triggerId == null) throw new IllegalArgumentException("\"triggerId\" is required but got null");
            

        return new AdditionalScopesRequestRequestBuilder(token, scopes, triggerId);
    }
    private okhttp3.Call listPermissionsCall(String token, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/apps.permissions.info";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (token != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("token", token));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "slackAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listPermissionsValidateBeforeCall(String token, final ApiCallback _callback) throws ApiException {
        return listPermissionsCall(token, _callback);

    }


    private ApiResponse<AppspermissionsListPermissionsResponse> listPermissionsWithHttpInfo(String token) throws ApiException {
        okhttp3.Call localVarCall = listPermissionsValidateBeforeCall(token, null);
        Type localVarReturnType = new TypeToken<AppspermissionsListPermissionsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call listPermissionsAsync(String token, final ApiCallback<AppspermissionsListPermissionsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listPermissionsValidateBeforeCall(token, _callback);
        Type localVarReturnType = new TypeToken<AppspermissionsListPermissionsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class ListPermissionsRequestBuilder {
        private String token;

        private ListPermissionsRequestBuilder() {
        }

        /**
         * Set token
         * @param token Authentication token. Requires scope: &#x60;none&#x60; (optional)
         * @return ListPermissionsRequestBuilder
         */
        public ListPermissionsRequestBuilder token(String token) {
            this.token = token;
            return this;
        }
        
        /**
         * Build call for listPermissions
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when used with an invalid token </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return listPermissionsCall(token, _callback);
        }


        /**
         * Execute listPermissions request
         * @return AppspermissionsListPermissionsResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when used with an invalid token </td><td>  -  </td></tr>
         </table>
         */
        public AppspermissionsListPermissionsResponse execute() throws ApiException {
            ApiResponse<AppspermissionsListPermissionsResponse> localVarResp = listPermissionsWithHttpInfo(token);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute listPermissions request with HTTP info returned
         * @return ApiResponse&lt;AppspermissionsListPermissionsResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when used with an invalid token </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<AppspermissionsListPermissionsResponse> executeWithHttpInfo() throws ApiException {
            return listPermissionsWithHttpInfo(token);
        }

        /**
         * Execute listPermissions request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when used with an invalid token </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<AppspermissionsListPermissionsResponse> _callback) throws ApiException {
            return listPermissionsAsync(token, _callback);
        }
    }

    /**
     * 
     * Returns list of permissions this app has on a team.
     * @return ListPermissionsRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Standard failure response when used with an invalid token </td><td>  -  </td></tr>
     </table>
     * API method documentation
     * @see <a href="https://api.slack.com/methods/apps.permissions.info"> Documentation</a>
     */
    public ListPermissionsRequestBuilder listPermissions() throws IllegalArgumentException {
        return new ListPermissionsRequestBuilder();
    }
}
