/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.AppsUninstallResponse;
import com.konfigthis.client.model.AppsUninstalldefaultResponse;
import com.konfigthis.client.model.AppseventauthorizationsGetListResponse;
import com.konfigthis.client.model.AppseventauthorizationsGetListdefaultResponse;
import com.konfigthis.client.model.AppspermissionsAdditionalScopesRequestResponse;
import com.konfigthis.client.model.AppspermissionsAdditionalScopesRequestdefaultResponse;
import com.konfigthis.client.model.AppspermissionsListPermissionsResponse;
import com.konfigthis.client.model.AppspermissionsListPermissionsdefaultResponse;
import com.konfigthis.client.model.AppspermissionsresourcesGetResourcesListResponse;
import com.konfigthis.client.model.AppspermissionsresourcesGetResourcesListdefaultResponse;
import com.konfigthis.client.model.AppspermissionsscopesGetListResponse;
import com.konfigthis.client.model.AppspermissionsscopesGetListdefaultResponse;
import com.konfigthis.client.model.AppspermissionsusersListUserGrantsResponse;
import com.konfigthis.client.model.AppspermissionsusersListUserGrantsdefaultResponse;
import com.konfigthis.client.model.AppspermissionsusersRequestModalResponse;
import com.konfigthis.client.model.AppspermissionsusersRequestModaldefaultResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class AppsApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AppsApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public AppsApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call additionalScopesRequestCall(String token, String scopes, String triggerId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/apps.permissions.request";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (token != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("token", token));
        }

        if (scopes != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("scopes", scopes));
        }

        if (triggerId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("trigger_id", triggerId));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "slackAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call additionalScopesRequestValidateBeforeCall(String token, String scopes, String triggerId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling additionalScopesRequest(Async)");
        }

        // verify the required parameter 'scopes' is set
        if (scopes == null) {
            throw new ApiException("Missing the required parameter 'scopes' when calling additionalScopesRequest(Async)");
        }

        // verify the required parameter 'triggerId' is set
        if (triggerId == null) {
            throw new ApiException("Missing the required parameter 'triggerId' when calling additionalScopesRequest(Async)");
        }

        return additionalScopesRequestCall(token, scopes, triggerId, _callback);

    }


    private ApiResponse<AppspermissionsAdditionalScopesRequestResponse> additionalScopesRequestWithHttpInfo(String token, String scopes, String triggerId) throws ApiException {
        okhttp3.Call localVarCall = additionalScopesRequestValidateBeforeCall(token, scopes, triggerId, null);
        Type localVarReturnType = new TypeToken<AppspermissionsAdditionalScopesRequestResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call additionalScopesRequestAsync(String token, String scopes, String triggerId, final ApiCallback<AppspermissionsAdditionalScopesRequestResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = additionalScopesRequestValidateBeforeCall(token, scopes, triggerId, _callback);
        Type localVarReturnType = new TypeToken<AppspermissionsAdditionalScopesRequestResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class AdditionalScopesRequestRequestBuilder {
        private final String token;
        private final String scopes;
        private final String triggerId;

        private AdditionalScopesRequestRequestBuilder(String token, String scopes, String triggerId) {
            this.token = token;
            this.scopes = scopes;
            this.triggerId = triggerId;
        }

        /**
         * Build call for additionalScopesRequest
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when trigger_id is invalid </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return additionalScopesRequestCall(token, scopes, triggerId, _callback);
        }


        /**
         * Execute additionalScopesRequest request
         * @return AppspermissionsAdditionalScopesRequestResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when trigger_id is invalid </td><td>  -  </td></tr>
         </table>
         */
        public AppspermissionsAdditionalScopesRequestResponse execute() throws ApiException {
            ApiResponse<AppspermissionsAdditionalScopesRequestResponse> localVarResp = additionalScopesRequestWithHttpInfo(token, scopes, triggerId);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute additionalScopesRequest request with HTTP info returned
         * @return ApiResponse&lt;AppspermissionsAdditionalScopesRequestResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when trigger_id is invalid </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<AppspermissionsAdditionalScopesRequestResponse> executeWithHttpInfo() throws ApiException {
            return additionalScopesRequestWithHttpInfo(token, scopes, triggerId);
        }

        /**
         * Execute additionalScopesRequest request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when trigger_id is invalid </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<AppspermissionsAdditionalScopesRequestResponse> _callback) throws ApiException {
            return additionalScopesRequestAsync(token, scopes, triggerId, _callback);
        }
    }

    /**
     * 
     * Allows an app to request additional scopes
     * @param token Authentication token. Requires scope: &#x60;none&#x60; (required)
     * @param scopes A comma separated list of scopes to request for (required)
     * @param triggerId Token used to trigger the permissions API (required)
     * @return AdditionalScopesRequestRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Standard failure response when trigger_id is invalid </td><td>  -  </td></tr>
     </table>
     * API method documentation
     * @see <a href="https://api.slack.com/methods/apps.permissions.request"> Documentation</a>
     */
    public AdditionalScopesRequestRequestBuilder additionalScopesRequest(String token, String scopes, String triggerId) throws IllegalArgumentException {
        if (token == null) throw new IllegalArgumentException("\"token\" is required but got null");
            

        if (scopes == null) throw new IllegalArgumentException("\"scopes\" is required but got null");
            

        if (triggerId == null) throw new IllegalArgumentException("\"triggerId\" is required but got null");
            

        return new AdditionalScopesRequestRequestBuilder(token, scopes, triggerId);
    }
    private okhttp3.Call getListCall(String token, String eventContext, String cursor, Integer limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/apps.event.authorizations.list";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (eventContext != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("event_context", eventContext));
        }

        if (cursor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cursor", cursor));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (token != null) {
            localVarHeaderParams.put("token", localVarApiClient.parameterToString(token));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "slackAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getListValidateBeforeCall(String token, String eventContext, String cursor, Integer limit, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling getList(Async)");
        }

        // verify the required parameter 'eventContext' is set
        if (eventContext == null) {
            throw new ApiException("Missing the required parameter 'eventContext' when calling getList(Async)");
        }

        return getListCall(token, eventContext, cursor, limit, _callback);

    }


    private ApiResponse<AppseventauthorizationsGetListResponse> getListWithHttpInfo(String token, String eventContext, String cursor, Integer limit) throws ApiException {
        okhttp3.Call localVarCall = getListValidateBeforeCall(token, eventContext, cursor, limit, null);
        Type localVarReturnType = new TypeToken<AppseventauthorizationsGetListResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getListAsync(String token, String eventContext, String cursor, Integer limit, final ApiCallback<AppseventauthorizationsGetListResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getListValidateBeforeCall(token, eventContext, cursor, limit, _callback);
        Type localVarReturnType = new TypeToken<AppseventauthorizationsGetListResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetListRequestBuilder {
        private final String token;
        private final String eventContext;
        private String cursor;
        private Integer limit;

        private GetListRequestBuilder(String token, String eventContext) {
            this.token = token;
            this.eventContext = eventContext;
        }

        /**
         * Set cursor
         * @param cursor  (optional)
         * @return GetListRequestBuilder
         */
        public GetListRequestBuilder cursor(String cursor) {
            this.cursor = cursor;
            return this;
        }
        
        /**
         * Set limit
         * @param limit  (optional)
         * @return GetListRequestBuilder
         */
        public GetListRequestBuilder limit(Integer limit) {
            this.limit = limit;
            return this;
        }
        
        /**
         * Build call for getList
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical success response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getListCall(token, eventContext, cursor, limit, _callback);
        }


        /**
         * Execute getList request
         * @return AppseventauthorizationsGetListResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical success response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public AppseventauthorizationsGetListResponse execute() throws ApiException {
            ApiResponse<AppseventauthorizationsGetListResponse> localVarResp = getListWithHttpInfo(token, eventContext, cursor, limit);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getList request with HTTP info returned
         * @return ApiResponse&lt;AppseventauthorizationsGetListResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical success response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<AppseventauthorizationsGetListResponse> executeWithHttpInfo() throws ApiException {
            return getListWithHttpInfo(token, eventContext, cursor, limit);
        }

        /**
         * Execute getList request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical success response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<AppseventauthorizationsGetListResponse> _callback) throws ApiException {
            return getListAsync(token, eventContext, cursor, limit, _callback);
        }
    }

    /**
     * 
     * Get a list of authorizations for the given event context. Each authorization represents an app installation that the event is visible to.
     * @param token Authentication token. Requires scope: &#x60;authorizations:read&#x60; (required)
     * @param eventContext  (required)
     * @return GetListRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Typical success response </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
     </table>
     * API method documentation
     * @see <a href="https://api.slack.com/methods/apps.event.authorizations.list"> Documentation</a>
     */
    public GetListRequestBuilder getList(String token, String eventContext) throws IllegalArgumentException {
        if (token == null) throw new IllegalArgumentException("\"token\" is required but got null");
            

        if (eventContext == null) throw new IllegalArgumentException("\"eventContext\" is required but got null");
            

        return new GetListRequestBuilder(token, eventContext);
    }
    private okhttp3.Call getList_0Call(String token, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/apps.permissions.scopes.list";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (token != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("token", token));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "slackAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getList_0ValidateBeforeCall(String token, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling getList_0(Async)");
        }

        return getList_0Call(token, _callback);

    }


    private ApiResponse<AppspermissionsscopesGetListResponse> getList_0WithHttpInfo(String token) throws ApiException {
        okhttp3.Call localVarCall = getList_0ValidateBeforeCall(token, null);
        Type localVarReturnType = new TypeToken<AppspermissionsscopesGetListResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getList_0Async(String token, final ApiCallback<AppspermissionsscopesGetListResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getList_0ValidateBeforeCall(token, _callback);
        Type localVarReturnType = new TypeToken<AppspermissionsscopesGetListResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetList0RequestBuilder {
        private final String token;

        private GetList0RequestBuilder(String token) {
            this.token = token;
        }

        /**
         * Build call for getList_0
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical successful paginated response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getList_0Call(token, _callback);
        }


        /**
         * Execute getList_0 request
         * @return AppspermissionsscopesGetListResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical successful paginated response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public AppspermissionsscopesGetListResponse execute() throws ApiException {
            ApiResponse<AppspermissionsscopesGetListResponse> localVarResp = getList_0WithHttpInfo(token);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getList_0 request with HTTP info returned
         * @return ApiResponse&lt;AppspermissionsscopesGetListResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical successful paginated response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<AppspermissionsscopesGetListResponse> executeWithHttpInfo() throws ApiException {
            return getList_0WithHttpInfo(token);
        }

        /**
         * Execute getList_0 request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical successful paginated response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<AppspermissionsscopesGetListResponse> _callback) throws ApiException {
            return getList_0Async(token, _callback);
        }
    }

    /**
     * 
     * Returns list of scopes this app has on a team.
     * @param token Authentication token. Requires scope: &#x60;none&#x60; (required)
     * @return GetList0RequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Typical successful paginated response </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
     </table>
     * API method documentation
     * @see <a href="https://api.slack.com/methods/apps.permissions.scopes.list"> Documentation</a>
     */
    public GetList0RequestBuilder getList_0(String token) throws IllegalArgumentException {
        if (token == null) throw new IllegalArgumentException("\"token\" is required but got null");
            

        return new GetList0RequestBuilder(token);
    }
    private okhttp3.Call getResourcesListCall(String token, String cursor, Integer limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/apps.permissions.resources.list";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (token != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("token", token));
        }

        if (cursor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cursor", cursor));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "slackAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getResourcesListValidateBeforeCall(String token, String cursor, Integer limit, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling getResourcesList(Async)");
        }

        return getResourcesListCall(token, cursor, limit, _callback);

    }


    private ApiResponse<AppspermissionsresourcesGetResourcesListResponse> getResourcesListWithHttpInfo(String token, String cursor, Integer limit) throws ApiException {
        okhttp3.Call localVarCall = getResourcesListValidateBeforeCall(token, cursor, limit, null);
        Type localVarReturnType = new TypeToken<AppspermissionsresourcesGetResourcesListResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getResourcesListAsync(String token, String cursor, Integer limit, final ApiCallback<AppspermissionsresourcesGetResourcesListResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = getResourcesListValidateBeforeCall(token, cursor, limit, _callback);
        Type localVarReturnType = new TypeToken<AppspermissionsresourcesGetResourcesListResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetResourcesListRequestBuilder {
        private final String token;
        private String cursor;
        private Integer limit;

        private GetResourcesListRequestBuilder(String token) {
            this.token = token;
        }

        /**
         * Set cursor
         * @param cursor Paginate through collections of data by setting the &#x60;cursor&#x60; parameter to a &#x60;next_cursor&#x60; attribute returned by a previous request&#39;s &#x60;response_metadata&#x60;. Default value fetches the first \&quot;page\&quot; of the collection. See [pagination](https://slack.dev) for more detail. (optional)
         * @return GetResourcesListRequestBuilder
         */
        public GetResourcesListRequestBuilder cursor(String cursor) {
            this.cursor = cursor;
            return this;
        }
        
        /**
         * Set limit
         * @param limit The maximum number of items to return. (optional)
         * @return GetResourcesListRequestBuilder
         */
        public GetResourcesListRequestBuilder limit(Integer limit) {
            this.limit = limit;
            return this;
        }
        
        /**
         * Build call for getResourcesList
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical successful paginated response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getResourcesListCall(token, cursor, limit, _callback);
        }


        /**
         * Execute getResourcesList request
         * @return AppspermissionsresourcesGetResourcesListResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical successful paginated response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public AppspermissionsresourcesGetResourcesListResponse execute() throws ApiException {
            ApiResponse<AppspermissionsresourcesGetResourcesListResponse> localVarResp = getResourcesListWithHttpInfo(token, cursor, limit);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getResourcesList request with HTTP info returned
         * @return ApiResponse&lt;AppspermissionsresourcesGetResourcesListResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical successful paginated response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<AppspermissionsresourcesGetResourcesListResponse> executeWithHttpInfo() throws ApiException {
            return getResourcesListWithHttpInfo(token, cursor, limit);
        }

        /**
         * Execute getResourcesList request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical successful paginated response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<AppspermissionsresourcesGetResourcesListResponse> _callback) throws ApiException {
            return getResourcesListAsync(token, cursor, limit, _callback);
        }
    }

    /**
     * 
     * Returns list of resource grants this app has on a team.
     * @param token Authentication token. Requires scope: &#x60;none&#x60; (required)
     * @return GetResourcesListRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Typical successful paginated response </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
     </table>
     * API method documentation
     * @see <a href="https://api.slack.com/methods/apps.permissions.resources.list"> Documentation</a>
     */
    public GetResourcesListRequestBuilder getResourcesList(String token) throws IllegalArgumentException {
        if (token == null) throw new IllegalArgumentException("\"token\" is required but got null");
            

        return new GetResourcesListRequestBuilder(token);
    }
    private okhttp3.Call listPermissionsCall(String token, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/apps.permissions.info";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (token != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("token", token));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "slackAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listPermissionsValidateBeforeCall(String token, final ApiCallback _callback) throws ApiException {
        return listPermissionsCall(token, _callback);

    }


    private ApiResponse<AppspermissionsListPermissionsResponse> listPermissionsWithHttpInfo(String token) throws ApiException {
        okhttp3.Call localVarCall = listPermissionsValidateBeforeCall(token, null);
        Type localVarReturnType = new TypeToken<AppspermissionsListPermissionsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call listPermissionsAsync(String token, final ApiCallback<AppspermissionsListPermissionsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listPermissionsValidateBeforeCall(token, _callback);
        Type localVarReturnType = new TypeToken<AppspermissionsListPermissionsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class ListPermissionsRequestBuilder {
        private String token;

        private ListPermissionsRequestBuilder() {
        }

        /**
         * Set token
         * @param token Authentication token. Requires scope: &#x60;none&#x60; (optional)
         * @return ListPermissionsRequestBuilder
         */
        public ListPermissionsRequestBuilder token(String token) {
            this.token = token;
            return this;
        }
        
        /**
         * Build call for listPermissions
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when used with an invalid token </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return listPermissionsCall(token, _callback);
        }


        /**
         * Execute listPermissions request
         * @return AppspermissionsListPermissionsResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when used with an invalid token </td><td>  -  </td></tr>
         </table>
         */
        public AppspermissionsListPermissionsResponse execute() throws ApiException {
            ApiResponse<AppspermissionsListPermissionsResponse> localVarResp = listPermissionsWithHttpInfo(token);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute listPermissions request with HTTP info returned
         * @return ApiResponse&lt;AppspermissionsListPermissionsResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when used with an invalid token </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<AppspermissionsListPermissionsResponse> executeWithHttpInfo() throws ApiException {
            return listPermissionsWithHttpInfo(token);
        }

        /**
         * Execute listPermissions request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when used with an invalid token </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<AppspermissionsListPermissionsResponse> _callback) throws ApiException {
            return listPermissionsAsync(token, _callback);
        }
    }

    /**
     * 
     * Returns list of permissions this app has on a team.
     * @return ListPermissionsRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Standard failure response when used with an invalid token </td><td>  -  </td></tr>
     </table>
     * API method documentation
     * @see <a href="https://api.slack.com/methods/apps.permissions.info"> Documentation</a>
     */
    public ListPermissionsRequestBuilder listPermissions() throws IllegalArgumentException {
        return new ListPermissionsRequestBuilder();
    }
    private okhttp3.Call listUserGrantsCall(String token, String cursor, Integer limit, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/apps.permissions.users.list";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (token != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("token", token));
        }

        if (cursor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("cursor", cursor));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "slackAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listUserGrantsValidateBeforeCall(String token, String cursor, Integer limit, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling listUserGrants(Async)");
        }

        return listUserGrantsCall(token, cursor, limit, _callback);

    }


    private ApiResponse<AppspermissionsusersListUserGrantsResponse> listUserGrantsWithHttpInfo(String token, String cursor, Integer limit) throws ApiException {
        okhttp3.Call localVarCall = listUserGrantsValidateBeforeCall(token, cursor, limit, null);
        Type localVarReturnType = new TypeToken<AppspermissionsusersListUserGrantsResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call listUserGrantsAsync(String token, String cursor, Integer limit, final ApiCallback<AppspermissionsusersListUserGrantsResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = listUserGrantsValidateBeforeCall(token, cursor, limit, _callback);
        Type localVarReturnType = new TypeToken<AppspermissionsusersListUserGrantsResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class ListUserGrantsRequestBuilder {
        private final String token;
        private String cursor;
        private Integer limit;

        private ListUserGrantsRequestBuilder(String token) {
            this.token = token;
        }

        /**
         * Set cursor
         * @param cursor Paginate through collections of data by setting the &#x60;cursor&#x60; parameter to a &#x60;next_cursor&#x60; attribute returned by a previous request&#39;s &#x60;response_metadata&#x60;. Default value fetches the first \&quot;page\&quot; of the collection. See [pagination](https://slack.dev) for more detail. (optional)
         * @return ListUserGrantsRequestBuilder
         */
        public ListUserGrantsRequestBuilder cursor(String cursor) {
            this.cursor = cursor;
            return this;
        }
        
        /**
         * Set limit
         * @param limit The maximum number of items to return. (optional)
         * @return ListUserGrantsRequestBuilder
         */
        public ListUserGrantsRequestBuilder limit(Integer limit) {
            this.limit = limit;
            return this;
        }
        
        /**
         * Build call for listUserGrants
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical successful paginated response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return listUserGrantsCall(token, cursor, limit, _callback);
        }


        /**
         * Execute listUserGrants request
         * @return AppspermissionsusersListUserGrantsResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical successful paginated response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public AppspermissionsusersListUserGrantsResponse execute() throws ApiException {
            ApiResponse<AppspermissionsusersListUserGrantsResponse> localVarResp = listUserGrantsWithHttpInfo(token, cursor, limit);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute listUserGrants request with HTTP info returned
         * @return ApiResponse&lt;AppspermissionsusersListUserGrantsResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical successful paginated response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<AppspermissionsusersListUserGrantsResponse> executeWithHttpInfo() throws ApiException {
            return listUserGrantsWithHttpInfo(token, cursor, limit);
        }

        /**
         * Execute listUserGrants request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical successful paginated response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<AppspermissionsusersListUserGrantsResponse> _callback) throws ApiException {
            return listUserGrantsAsync(token, cursor, limit, _callback);
        }
    }

    /**
     * 
     * Returns list of user grants and corresponding scopes this app has on a team.
     * @param token Authentication token. Requires scope: &#x60;none&#x60; (required)
     * @return ListUserGrantsRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Typical successful paginated response </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
     </table>
     * API method documentation
     * @see <a href="https://api.slack.com/methods/apps.permissions.users.list"> Documentation</a>
     */
    public ListUserGrantsRequestBuilder listUserGrants(String token) throws IllegalArgumentException {
        if (token == null) throw new IllegalArgumentException("\"token\" is required but got null");
            

        return new ListUserGrantsRequestBuilder(token);
    }
    private okhttp3.Call requestModalCall(String token, String scopes, String triggerId, String user, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/apps.permissions.users.request";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (token != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("token", token));
        }

        if (scopes != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("scopes", scopes));
        }

        if (triggerId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("trigger_id", triggerId));
        }

        if (user != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("user", user));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "slackAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call requestModalValidateBeforeCall(String token, String scopes, String triggerId, String user, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling requestModal(Async)");
        }

        // verify the required parameter 'scopes' is set
        if (scopes == null) {
            throw new ApiException("Missing the required parameter 'scopes' when calling requestModal(Async)");
        }

        // verify the required parameter 'triggerId' is set
        if (triggerId == null) {
            throw new ApiException("Missing the required parameter 'triggerId' when calling requestModal(Async)");
        }

        // verify the required parameter 'user' is set
        if (user == null) {
            throw new ApiException("Missing the required parameter 'user' when calling requestModal(Async)");
        }

        return requestModalCall(token, scopes, triggerId, user, _callback);

    }


    private ApiResponse<AppspermissionsusersRequestModalResponse> requestModalWithHttpInfo(String token, String scopes, String triggerId, String user) throws ApiException {
        okhttp3.Call localVarCall = requestModalValidateBeforeCall(token, scopes, triggerId, user, null);
        Type localVarReturnType = new TypeToken<AppspermissionsusersRequestModalResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call requestModalAsync(String token, String scopes, String triggerId, String user, final ApiCallback<AppspermissionsusersRequestModalResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = requestModalValidateBeforeCall(token, scopes, triggerId, user, _callback);
        Type localVarReturnType = new TypeToken<AppspermissionsusersRequestModalResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class RequestModalRequestBuilder {
        private final String token;
        private final String scopes;
        private final String triggerId;
        private final String user;

        private RequestModalRequestBuilder(String token, String scopes, String triggerId, String user) {
            this.token = token;
            this.scopes = scopes;
            this.triggerId = triggerId;
            this.user = user;
        }

        /**
         * Build call for requestModal
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when trigger_id is invalid </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return requestModalCall(token, scopes, triggerId, user, _callback);
        }


        /**
         * Execute requestModal request
         * @return AppspermissionsusersRequestModalResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when trigger_id is invalid </td><td>  -  </td></tr>
         </table>
         */
        public AppspermissionsusersRequestModalResponse execute() throws ApiException {
            ApiResponse<AppspermissionsusersRequestModalResponse> localVarResp = requestModalWithHttpInfo(token, scopes, triggerId, user);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute requestModal request with HTTP info returned
         * @return ApiResponse&lt;AppspermissionsusersRequestModalResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when trigger_id is invalid </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<AppspermissionsusersRequestModalResponse> executeWithHttpInfo() throws ApiException {
            return requestModalWithHttpInfo(token, scopes, triggerId, user);
        }

        /**
         * Execute requestModal request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Standard failure response when trigger_id is invalid </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<AppspermissionsusersRequestModalResponse> _callback) throws ApiException {
            return requestModalAsync(token, scopes, triggerId, user, _callback);
        }
    }

    /**
     * 
     * Enables an app to trigger a permissions modal to grant an app access to a user access scope.
     * @param token Authentication token. Requires scope: &#x60;none&#x60; (required)
     * @param scopes A comma separated list of user scopes to request for (required)
     * @param triggerId Token used to trigger the request (required)
     * @param user The user this scope is being requested for (required)
     * @return RequestModalRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Standard success response when used with a user token </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Standard failure response when trigger_id is invalid </td><td>  -  </td></tr>
     </table>
     * API method documentation
     * @see <a href="https://api.slack.com/methods/apps.permissions.users.request"> Documentation</a>
     */
    public RequestModalRequestBuilder requestModal(String token, String scopes, String triggerId, String user) throws IllegalArgumentException {
        if (token == null) throw new IllegalArgumentException("\"token\" is required but got null");
            

        if (scopes == null) throw new IllegalArgumentException("\"scopes\" is required but got null");
            

        if (triggerId == null) throw new IllegalArgumentException("\"triggerId\" is required but got null");
            

        if (user == null) throw new IllegalArgumentException("\"user\" is required but got null");
            

        return new RequestModalRequestBuilder(token, scopes, triggerId, user);
    }
    private okhttp3.Call uninstallCall(String token, String clientId, String clientSecret, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/apps.uninstall";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (token != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("token", token));
        }

        if (clientId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("client_id", clientId));
        }

        if (clientSecret != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("client_secret", clientSecret));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "slackAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call uninstallValidateBeforeCall(String token, String clientId, String clientSecret, final ApiCallback _callback) throws ApiException {
        return uninstallCall(token, clientId, clientSecret, _callback);

    }


    private ApiResponse<AppsUninstallResponse> uninstallWithHttpInfo(String token, String clientId, String clientSecret) throws ApiException {
        okhttp3.Call localVarCall = uninstallValidateBeforeCall(token, clientId, clientSecret, null);
        Type localVarReturnType = new TypeToken<AppsUninstallResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call uninstallAsync(String token, String clientId, String clientSecret, final ApiCallback<AppsUninstallResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = uninstallValidateBeforeCall(token, clientId, clientSecret, _callback);
        Type localVarReturnType = new TypeToken<AppsUninstallResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class UninstallRequestBuilder {
        private String token;
        private String clientId;
        private String clientSecret;

        private UninstallRequestBuilder() {
        }

        /**
         * Set token
         * @param token Authentication token. Requires scope: &#x60;none&#x60; (optional)
         * @return UninstallRequestBuilder
         */
        public UninstallRequestBuilder token(String token) {
            this.token = token;
            return this;
        }
        
        /**
         * Set clientId
         * @param clientId Issued when you created your application. (optional)
         * @return UninstallRequestBuilder
         */
        public UninstallRequestBuilder clientId(String clientId) {
            this.clientId = clientId;
            return this;
        }
        
        /**
         * Set clientSecret
         * @param clientSecret Issued when you created your application. (optional)
         * @return UninstallRequestBuilder
         */
        public UninstallRequestBuilder clientSecret(String clientSecret) {
            this.clientSecret = clientSecret;
            return this;
        }
        
        /**
         * Build call for uninstall
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical success response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return uninstallCall(token, clientId, clientSecret, _callback);
        }


        /**
         * Execute uninstall request
         * @return AppsUninstallResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical success response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public AppsUninstallResponse execute() throws ApiException {
            ApiResponse<AppsUninstallResponse> localVarResp = uninstallWithHttpInfo(token, clientId, clientSecret);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute uninstall request with HTTP info returned
         * @return ApiResponse&lt;AppsUninstallResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical success response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<AppsUninstallResponse> executeWithHttpInfo() throws ApiException {
            return uninstallWithHttpInfo(token, clientId, clientSecret);
        }

        /**
         * Execute uninstall request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical success response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<AppsUninstallResponse> _callback) throws ApiException {
            return uninstallAsync(token, clientId, clientSecret, _callback);
        }
    }

    /**
     * 
     * Uninstalls your app from a workspace.
     * @return UninstallRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Typical success response </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
     </table>
     * API method documentation
     * @see <a href="https://api.slack.com/methods/apps.uninstall"> Documentation</a>
     */
    public UninstallRequestBuilder uninstall() throws IllegalArgumentException {
        return new UninstallRequestBuilder();
    }
}
