/*
 * Slack Web API
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.RtmConnectResponse;
import com.konfigthis.client.model.RtmConnectdefaultResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class RtmApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public RtmApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public RtmApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call connectCall(String token, Boolean batchPresenceAware, Boolean presenceSub, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/rtm.connect";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (token != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("token", token));
        }

        if (batchPresenceAware != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("batch_presence_aware", batchPresenceAware));
        }

        if (presenceSub != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("presence_sub", presenceSub));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "slackAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call connectValidateBeforeCall(String token, Boolean batchPresenceAware, Boolean presenceSub, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'token' is set
        if (token == null) {
            throw new ApiException("Missing the required parameter 'token' when calling connect(Async)");
        }

        return connectCall(token, batchPresenceAware, presenceSub, _callback);

    }


    private ApiResponse<RtmConnectResponse> connectWithHttpInfo(String token, Boolean batchPresenceAware, Boolean presenceSub) throws ApiException {
        okhttp3.Call localVarCall = connectValidateBeforeCall(token, batchPresenceAware, presenceSub, null);
        Type localVarReturnType = new TypeToken<RtmConnectResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call connectAsync(String token, Boolean batchPresenceAware, Boolean presenceSub, final ApiCallback<RtmConnectResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = connectValidateBeforeCall(token, batchPresenceAware, presenceSub, _callback);
        Type localVarReturnType = new TypeToken<RtmConnectResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class ConnectRequestBuilder {
        private final String token;
        private Boolean batchPresenceAware;
        private Boolean presenceSub;

        private ConnectRequestBuilder(String token) {
            this.token = token;
        }

        /**
         * Set batchPresenceAware
         * @param batchPresenceAware Batch presence deliveries via subscription. Enabling changes the shape of &#x60;presence_change&#x60; events. See [batch presence](https://slack.dev). (optional)
         * @return ConnectRequestBuilder
         */
        public ConnectRequestBuilder batchPresenceAware(Boolean batchPresenceAware) {
            this.batchPresenceAware = batchPresenceAware;
            return this;
        }
        
        /**
         * Set presenceSub
         * @param presenceSub Only deliver presence events when requested by subscription. See [presence subscriptions](https://slack.dev). (optional)
         * @return ConnectRequestBuilder
         */
        public ConnectRequestBuilder presenceSub(Boolean presenceSub) {
            this.presenceSub = presenceSub;
            return this;
        }
        
        /**
         * Build call for connect
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical success response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return connectCall(token, batchPresenceAware, presenceSub, _callback);
        }


        /**
         * Execute connect request
         * @return RtmConnectResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical success response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public RtmConnectResponse execute() throws ApiException {
            ApiResponse<RtmConnectResponse> localVarResp = connectWithHttpInfo(token, batchPresenceAware, presenceSub);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute connect request with HTTP info returned
         * @return ApiResponse&lt;RtmConnectResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical success response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<RtmConnectResponse> executeWithHttpInfo() throws ApiException {
            return connectWithHttpInfo(token, batchPresenceAware, presenceSub);
        }

        /**
         * Execute connect request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td> Typical success response </td><td>  -  </td></tr>
            <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<RtmConnectResponse> _callback) throws ApiException {
            return connectAsync(token, batchPresenceAware, presenceSub, _callback);
        }
    }

    /**
     * 
     * Starts a Real Time Messaging session.
     * @param token Authentication token. Requires scope: &#x60;rtm:stream&#x60; (required)
     * @return ConnectRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Typical success response </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Typical error response </td><td>  -  </td></tr>
     </table>
     * API method documentation
     * @see <a href="https://api.slack.com/methods/rtm.connect"> Documentation</a>
     */
    public ConnectRequestBuilder connect(String token) throws IllegalArgumentException {
        if (token == null) throw new IllegalArgumentException("\"token\" is required but got null");
            

        return new ConnectRequestBuilder(token);
    }
}
